In [73]:
# External libraries for data processing
import numpy as np
import pandas as pd
import sklearn as sk
#To render graphs within notebook
%matplotlib inline
import matplotlib.pyplot as plt
import joblib 
import os

# Versions of libraries
print("Numpy version: {}".format(np.__version__))
print("Pandas version: {}".format(pd.__version__))
print("Scikit version: {}".format(sk.__version__))

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer

Numpy version: 1.24.3
Pandas version: 1.5.3
Scikit version: 1.3.0

In [74]:
path = "C:/Project/Data/"

In [75]:
file = "hosp/admissions.csv"
full_path = path + file

df_admissions = pd.read_csv(full_path)

df_admissions['dischtime'] = pd.to_datetime(df_admissions['dischtime'], format='%d/%m/%Y %H:%M')
df_admissions['admittime'] = pd.to_datetime(df_admissions['admittime'], format='%d/%m/%Y %H:%M')

df_admittime= pd.DataFrame()
df_admittime['hadm_id'] = df_admissions['hadm_id']
df_admittime['admittime'] = df_admissions['admittime']

In [76]:
def convert_to_days(duration_str):
    parts = duration_str.split(' days ')  # Split string into form ['22', '20:55:00']
    days = float(parts[0])  # Extract number of days and convert to float
    time_parts = parts[1].split(':')  # Split time part (hh:mm:ss) ['20', '55', '00']
    hours = float(time_parts[0])  # Extract hours and convert to float
    minutes = float(time_parts[1])  # Extract minutes and convert to float
    seconds = float(time_parts[2])  # Extract seconds and convert to float
    total_days = days + (hours / 24) + (minutes / (24 * 60)) + (seconds / (24 * 3600))  # Calculate total days
    return total_days

### Target variable calculation

Pharmacy table has formulary, dosing and other info for prescribed medications 
Dose, number of formulary doses, medication route, duration of prescription


All features:
Subject_id, hadm_id, pharmacy_id, poe_id, starttime, stoptime, medication, proc_type, status, entertime, verifiedtime, route, frequency, disp_sched, infusion_type, sliding_scale, lockout_interval, basal_rate, one_hr_max, doses_per_24_hrs, duration, duration_interval, expiration_value, expiration_unit, expirationdate, dispensation, fill_quantity

In [77]:
file = "hosp/pharmacy.csv"
full_path = path + file

df_pharmacy = pd.read_csv(full_path)

In [78]:
df_pharmacy['medication'].value_counts()

Insulin                                                                        956
Sodium Chloride 0.9%  Flush                                                    587
Furosemide                                                                     510
Potassium Chloride                                                             437
Heparin                                                                        390
                                                                              ...
RiTONAvir                                                                        1
PHENObarbital - ICU Alcohol Withdrawal (Loading Dose 2 and 3)                    1
Orthopedic Solution                                                              1
Hemorrhoidal Suppository                                                         1
Alteplase 1mg/2mL ( Clearance ie. PICC, midline, tunneled access line, PA )      1
Name: medication, Length: 583, dtype: int64

In [79]:
df_pharmacy['dispensation'].value_counts()

Omnicell                    10703
Floor Stock Item             1316
Distribution-Floor Stock      962
OmniCell                      661
LET CALL                      648
IV MED                        484
Bulk Item                     260
Pharmacy Meds                 163
PATIENT MAY TAKE OWN           17
NON FORM BULK MED               1
Self Med Program                1
Name: dispensation, dtype: int64

In [80]:
# admission id and one hot encoding of the icd_codes (or drgcodes) related to it
# first one-hot encode the code column and then aggregate by id

In [81]:
df_pharmacy = df_pharmacy.drop(columns=['pharmacy_id','poe_id','starttime','stoptime','subject_id',
                                       'proc_type','status','entertime','verifiedtime','route','frequency',
                                       'disp_sched','infusion_type','sliding_scale','lockout_interval','basal_rate',
                                       'one_hr_max','doses_per_24_hrs','duration','duration_interval','expiration_value',
                                       'expiration_unit','expirationdate','dispensation','fill_quantity'])

In [82]:
df_pharmacy.head()

    hadm_id        medication
0  28166872         Midazolam
1  28166872         Midazolam
2  28166872  Fentanyl Citrate
3  28166872  Fentanyl Citrate
4  28166872         Lorazepam

In [83]:
one_hot_encoded = pd.get_dummies(df_pharmacy['medication'])

df_encoded = pd.concat([df_pharmacy[['hadm_id']], one_hot_encoded], axis=1)

df_aggregated = df_encoded.groupby('hadm_id').sum().reset_index()

# If you want to replace NaN values (where the category did not appear for a particular ID) with 0
df_aggregated = df_aggregated.fillna(0)

In [84]:
df_pharmacy = df_aggregated
df_pharmacy

,hadm_id,1,2,23.4% Sodium Chloride,ALPRAZolam,AcetaZOLamide,Acetaminophen,Acetaminophen (Liquid),Acetaminophen IV,Acetaminophen w/Codeine,...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,20044587,0,0,0,0,0,3,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,20093566,0,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,20192635,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,20199380,0,0,0,0,0,3,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,20214994,0,0,0,0,0,2,4,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,29820177,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
246,29839885,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
247,29842315,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
248,29858644,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
249,29974575,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [85]:
df_pharmacy = df_pharmacy.drop(columns=['1','2'])

In [86]:
df_pharmacy

,hadm_id,23.4% Sodium Chloride,ALPRAZolam,AcetaZOLamide,Acetaminophen,Acetaminophen (Liquid),Acetaminophen IV,Acetaminophen w/Codeine,Acetaminophen-Caff-Butalbital,Acetylcysteine (IV),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,20044587,0,0,0,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,20093566,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,20192635,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,20199380,0,0,0,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,20214994,0,0,0,2,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,29820177,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
246,29839885,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
247,29842315,0,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
248,29858644,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
249,29974575,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

#### Prescription

Subject_id, hadm_id, pharmacy_id, poe_id, poe_seq, order_provider_id, starttime, stoptime, drug_type, drug, formulary_drug_cd, gsn, ndc, prod_strength, form_rx, dose_val_rx, dose_unit_rx, form_val_disp, form_unit_disp, doses_per_24_hrs, route

In [87]:
file = "hosp/prescriptions.csv"
full_path = path + file

df_prescriptions = pd.read_csv(full_path)

In [88]:
df_prescriptions['drug'].value_counts()

Insulin                        915
0.9% Sodium Chloride           810
Potassium Chloride             610
Sodium Chloride 0.9%  Flush    585
Furosemide                     510
                              ...
Cefpodoxime Proxetil             1
Felodipine                       1
Estrogens Conjugated             1
Donepezil                        1
Carbamide Peroxide 6.5%          1
Name: drug, Length: 631, dtype: int64

In [89]:
df_prescriptions = df_prescriptions.drop(columns=['pharmacy_id','poe_id','poe_seq','order_provider_id','starttime',
                                       'stoptime','drug_type','formulary_drug_cd','gsn','ndc','prod_strength',
                                       'form_rx','dose_val_rx','dose_unit_rx','form_val_disp','form_unit_disp',
                                       'doses_per_24_hrs','route','subject_id'])

In [90]:
df_prescriptions.head()

    hadm_id              drug
0  28166872  Fentanyl Citrate
1  28166872  Fentanyl Citrate
2  28166872         Lorazepam
3  28166872         Midazolam
4  28166872         Midazolam

In [91]:
one_hot_encoded = pd.get_dummies(df_prescriptions['drug'])

df_encoded = pd.concat([df_prescriptions[['hadm_id']], one_hot_encoded], axis=1)

df_aggregated = df_encoded.groupby('hadm_id').sum().reset_index()

# If you want to replace NaN values (where the category did not appear for a particular ID) with 0
df_aggregated = df_aggregated.fillna(0)

In [92]:
df_prescriptions = df_aggregated
df_prescriptions

,hadm_id,*NF* Ertapenem Sodium,0.45% Sodium Chloride,0.83% Sodium Chloride,0.9% NaCl (EXCEL/ViaFLO BAG),0.9% Sodium Chloride,0.9% Sodium Chloride (Mini Bag Plus),23.4% Sodium Chloride,5% Dextrose,5% Dextrose (EXCEL BAG),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,20044587,0,0,0,0,4,0,0,2,0,...,0,0,0,0,0,0,0,0,0,0
1,20093566,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,20192635,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,20199380,0,0,0,0,3,0,0,9,0,...,0,0,0,0,0,0,0,0,0,0
4,20214994,0,0,0,0,4,2,0,11,5,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,29820177,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
246,29839885,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
247,29842315,0,0,0,0,2,0,0,3,4,...,0,0,0,0,0,0,0,0,0,0
248,29858644,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
249,29974575,0,0,0,0,3,0,0,2,0,...,0,0,0,0,0,0,0,0,0,0

### omr

Does not have hadm_id

### admissions

No info relevant to medication

### emar

Contains information about the administration of medication (so not useful to predict what meds to give)

### emar_detail

Same as emar

### hcpcsevents

Contains info about billable events but for like 40 different admissions, could combine to another

In [80]:
# d_hcpcs has longer descriptions (connected by code) but no other useful info

In [56]:
file = "hosp/hcpcsevents.csv"
full_path = path + file

df_hcpcsevents = pd.read_csv(full_path)

In [ ]:
# df_hcpcsevents['hadm_id'].value_counts()
# hadm_id not unique

In [46]:
# patient, admission, date, uniquely identifying billed code, sequence number, description

To drop: subject_id, chartdate, hcpcs_cd (code that links to longer description in d_hcpcs)

In [57]:
df_hcpcsevents

,subject_id,hadm_id,chartdate,hcpcs_cd,seq_num,short_description
0,10005348,29176490,2129-05-22,93454,1,Cardiovascular
1,10005348,29176490,2129-05-22,92921,2,Cardiovascular
2,10004457,21039249,2140-09-17,92980,1,Cardiovascular
3,10004457,25559382,2148-09-14,93455,1,Cardiovascular
4,10039708,27504040,2142-07-06,64415,2,Nervous system
...,...,...,...,...,...,...
56,10039708,27504040,2142-07-06,99219,3,Hospital observation services
57,10039708,22999601,2142-05-15,99219,1,Hospital observation services
58,10035631,29654498,2113-07-17,99218,3,Hospital observation services
59,10012853,20457729,2177-11-03,99219,2,Hospital observation services
60,10040025,27125816,2143-03-18,99218,2,Hospital observation services

In [58]:
# Make a feature for days_since_admission using chartdate - admittime

# Convert to datetime
df_hcpcsevents['chartdate'] = pd.to_datetime(df_hcpcsevents['chartdate'], format='%Y/%m/%d %H:%M')

# Add admittime column from other dataframe
df_hcpcsevents = df_hcpcsevents.merge(df_admittime, on='hadm_id', how='left')

# Discard the time part and keep only the date
df_hcpcsevents['admittime'] = df_hcpcsevents['admittime'].dt.date
df_hcpcsevents['chartdate'] = df_hcpcsevents['chartdate'].dt.date

df_hcpcsevents['days_since_admission'] = df_hcpcsevents['chartdate'] - df_hcpcsevents['admittime']

# Fill any non time values
df_hcpcsevents['days_since_admission'] = df_hcpcsevents['days_since_admission'].fillna(pd.Timedelta(0))

In [59]:
df_hcpcsevents['days_since_admission'].value_counts()

0 days    58
1 days     3
Name: days_since_admission, dtype: int64

In [60]:
df_hcpcsevents = df_hcpcsevents.drop(columns=['subject_id','chartdate','hcpcs_cd'])
# Not enough samples to include code as after encoding there would be a lot more features

In [61]:
df_hcpcsevents = pd.get_dummies(df_hcpcsevents, columns=['short_description'])

In [62]:
df_hcpcsevents

,hadm_id,seq_num,admittime,days_since_admission,short_description_Cardiovascular,short_description_Cardiovascular system,short_description_Digestive system,short_description_Endocrine system,short_description_Hemic and lymphatic systems,short_description_Hospital observation per hr,short_description_Hospital observation services,short_description_Integumentary system,short_description_Musculoskeletal system,short_description_Nervous system,short_description_Perc drug-el cor stent sing
0,29176490,1,2129-05-22,0 days,1,0,0,0,0,0,0,0,0,0,0
1,29176490,2,2129-05-22,0 days,1,0,0,0,0,0,0,0,0,0,0
2,21039249,1,2140-09-17,0 days,1,0,0,0,0,0,0,0,0,0,0
3,25559382,1,2148-09-14,0 days,1,0,0,0,0,0,0,0,0,0,0
4,27504040,2,2142-07-06,0 days,0,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,27504040,3,2142-07-06,0 days,0,0,0,0,0,0,1,0,0,0,0
57,22999601,1,2142-05-15,0 days,0,0,0,0,0,0,1,0,0,0,0
58,29654498,3,2113-07-17,0 days,0,0,0,0,0,0,1,0,0,0,0
59,20457729,2,2177-11-03,0 days,0,0,0,0,0,0,1,0,0,0,0
60,27125816,2,2143-03-18,0 days,0,0,0,0,0,0,1,0,0,0,0

#### Split into train and test

In [63]:
data = df_hcpcsevents

# Split the dataset into training and testing sets
hcpcsevents_data_train, hcpcsevents_data_test = train_test_split(data, test_size=0.2, random_state=42)

# Print the shapes of the resulting training and testing sets
print("Training set shape:", hcpcsevents_data_train.shape)
print("Testing set shape:", hcpcsevents_data_test.shape)

Training set shape: (48, 15)
Testing set shape: (13, 15)

#### Dimensionality reduction

In [ ]:
# Need to reduce from 14 to 9

In [64]:
path = "C:/Users/jenni/OneDrive/Desktop/IP/"
file = "hcpcsevents_data_train.csv"
full_path = path + file

hcpcsevents_data_train = pd.read_csv(full_path)
hcpcsevents_data_train

path = "C:/Users/jenni/OneDrive/Desktop/IP/"
file = "hcpcsevents_data_test.csv"
full_path = path + file

hcpcsevents_data_test = pd.read_csv(full_path)
hcpcsevents_data_test

In [65]:
# drop admittime and convert days into float
hcpcsevents_data_train = hcpcsevents_data_train.drop(columns=['admittime','hadm_id'])
# hcpcsevents_data_train['days_since_admission'] = hcpcsevents_data_train['days_since_admission'].apply(convert_to_days)
hcpcsevents_data_test = hcpcsevents_data_test.drop(columns=['admittime','hadm_id'])
# hcpcsevents_data_test['days_since_admission'] = hcpcsevents_data_test['days_since_admission'].apply(convert_to_days)

hcpcsevents_data_train['days_since_admission'] = hcpcsevents_data_train['days_since_admission'].astype(str)
hcpcsevents_data_train['days_since_admission'] = hcpcsevents_data_train['days_since_admission'].str.split().str[0].astype(int)
hcpcsevents_data_test['days_since_admission'] = hcpcsevents_data_test['days_since_admission'].astype(str)
hcpcsevents_data_test['days_since_admission'] = hcpcsevents_data_test['days_since_admission'].str.split().str[0].astype(int)

In [66]:
from sklearn.decomposition import TruncatedSVD

# Number of desired features (components)
n_components = 9

# Initialize Truncated SVD with the desired number of components
svd = TruncatedSVD(n_components=n_components)

# Fit the Truncated SVD model to the sparse matrix and transform the data
svd.fit(hcpcsevents_data_train)
hcpcsevents_data_train = svd.transform(hcpcsevents_data_train)

# Get the explained variance ratio (how much variance is explained by each component)
explained_variance_ratio = svd.explained_variance_ratio_

# Print the transformed matrix and explained variance ratio
# print("Transformed Matrix:")
# print(transformed_matrix)
print("\nExplained Variance Ratio:")
print(explained_variance_ratio)

print("\n Amount of original variance conserved:", np.sum(svd.explained_variance_ratio_))

Explained Variance Ratio:
[0.43713458 0.24268566 0.10206493 0.05400726 0.03833628 0.02801852
 0.02066158 0.01417428 0.01413247]

 Amount of original variance conserved: 0.95121556402236

In [67]:
hcpcsevents_data_test = svd.transform(hcpcsevents_data_test)

In [68]:
# # uncomment and run if changes are made
path = "C:/Users/jenni/OneDrive/Desktop/IP/"
pd.DataFrame(hcpcsevents_data_train).to_csv('hcpcsevents_data_train.csv', index=False)
pd.DataFrame(hcpcsevents_data_test).to_csv('hcpcsevents_data_test.csv', index=False)

In [70]:
pd.DataFrame(hcpcsevents_data_train)

# The order I hope is preserved and matches with hcpcsevents_pharmacy_label_train

,0,1,2,3,4,5,6,7,8
0,0.988436,0.236146,0.186962,-0.538382,0.789376,-6.659562e-16,0.120296,1.139833e-16,1.574203e-17
1,1.058110,0.483952,-0.779677,0.153909,0.070386,-1.716890e-17,0.064510,-3.073938e-17,-5.177687e-17
2,1.937252,0.393564,0.227114,-0.245865,-0.180166,-1.380743e-15,-0.477784,-3.198821e-01,-6.007388e-01
3,3.956854,0.903655,0.957269,0.763698,0.141686,1.291114e-16,0.013125,1.186673e-16,6.502535e-17
4,2.994714,0.717982,0.858989,0.854365,0.198774,1.291114e-16,0.088416,1.186673e-16,6.502535e-17
5,1.200510,-0.738512,-0.101706,0.019678,0.016419,2.856471e-16,0.016847,-4.628839e-16,-4.508902e-16
6,1.937252,0.393564,0.227114,-0.245865,-0.180166,-1.773079e-15,-0.477784,6.972869e-02,1.490970e-01
7,1.200510,-0.738512,-0.101706,0.019678,0.016419,2.856471e-16,0.016847,-4.628839e-16,-4.508902e-16
8,1.255459,-0.685677,0.164826,0.602495,0.222680,-6.263150e-15,0.274095,9.987341e-15,9.893670e-15
9,2.919069,0.616096,0.385287,-0.522457,-0.562158,-3.713907e-01,0.471533,6.185344e-17,1.288170e-16
10,1.058110,0.483952,-0.779677,0.153909,0.070386,-1.716890e-17,0.064510,-3.073938e-17,-5.177687e-17
11,1.200510,-0.738512,-0.101706,0.019678,0.016419,2.856471e-16,0.016847,-4.628839e-16,-4.508902e-16
12,1.058110,0.483952,-0.779677,0.153909,0.070386,-1.716890e-17,0.064510,-3.073938e-17,-5.177687e-17
13,0.968626,0.196782,0.113557,-0.122932,-0.090083,-9.975619e-16,-0.238892,-3.114892e-01,7.804859e-01
14,2.982391,0.855299,-0.583119,-0.027425,-0.043790,-1.716890e-17,-0.086071,-3.073938e-17,-5.177687e-17
15,1.200510,-0.738512,-0.101706,0.019678,0.016419,2.856471e-16,0.016847,-4.628839e-16,-4.508902e-16
16,0.975199,0.209304,0.134459,-0.190849,-0.213445,9.284767e-01,0.203671,1.034115e-16,4.252922e-16
17,1.200510,-0.738512,-0.101706,0.019678,0.016419,2.856471e-16,0.016847,-4.628839e-16,-4.508902e-16
18,1.200510,-0.738512,-0.101706,0.019678,0.016419,2.856471e-16,0.016847,-4.628839e-16,-4.508902e-16
19,1.200510,-0.738512,-0.101706,0.019678,0.016419,2.856471e-16,0.016847,-4.628839e-16,-4.508902e-16
20,1.200510,-0.738512,-0.101706,0.019678,0.016419,2.856471e-16,0.016847,-4.628839e-16,-4.508902e-16
21,1.200510,-0.738512,-0.101706,0.019678,0.016419,2.856471e-16,0.016847,-4.628839e-16,-4.508902e-16
22,0.968626,0.196782,0.113557,-0.122932,-0.090083,-8.884187e-16,-0.238892,8.887445e-01,5.177632e-02
23,3.124791,-0.367165,0.094853,-0.161656,-0.097758,2.856471e-16,-0.133734,-4.628839e-16,-4.508902e-16
24,1.058110,0.483952,-0.779677,0.153909,0.070386,-1.716890e-17,0.064510,-3.073938e-17,-5.177687e-17
25,2.982391,0.855299,-0.583119,-0.027425,-0.043790,-1.716890e-17,-0.086071,-3.073938e-17,-5.177687e-17
26,1.200510,-0.738512,-0.101706,0.019678,0.016419,2.856471e-16,0.016847,-4.628839e-16,-4.508902e-16
27,2.162651,-0.552839,-0.003427,-0.070989,-0.040670,2.856471e-16,-0.058444,-4.628839e-16,-4.508902e-16
28,1.200510,-0.738512,-0.101706,0.019678,0.016419,2.856471e-16,0.016847,-4.628839e-16,-4.508902e-16
29,1.950577,0.421820,0.285242,-0.629049,0.732287,-6.659562e-16,0.045005,1.139833e-16,1.574203e-17
30,1.200510,-0.738512,-0.101706,0.019678,0.016419,2.856471e-16,0.016847,-4.628839e-16,-4.508902e-16
31,0.988436,0.236146,0.186962,-0.538382,0.789376,-6.659562e-16,0.120296,1.139833e-16,1.574203e-17
32,1.956928,0.430423,0.287008,-0.431789,-0.505070,-3.713907e-01,0.546824,6.185344e-17,1.288170e-16
33,1.200510,-0.738512,-0.101706,0.019678,0.016419,2.856471e-16,0.016847,-4.628839e-16,-4.508902e-16
34,2.162651,-0.552839,-0.003427,-0.070989,-0.040670,2.856471e-16,-0.058444,-4.628839e-16,-4.508902e-16
35,1.200510,-0.738512,-0.101706,0.019678,0.016419,2.856471e-16,0.016847,-4.628839e-16,-4.508902e-16
36,1.058110,0.483952,-0.779677,0.153909,0.070386,-1.716890e-17,0.064510,-3.073938e-17,-5.177687e-17
37,0.975199,0.209304,0.134459,-0.190849,-0.213445,9.284767e-01,0.203671,1.034115e-16,4.252922e-16
38,1.200510,-0.738512,-0.101706,0.019678,0.016419,2.856471e-16,0.016847,-4.628839e-16,-4.508902e-16
39,4.086932,-0.181492,0.193132,-0.252323,-0.154846,2.856471e-16,-0.209025,-4.628839e-16,-4.508902e-16
40,2.020251,0.669625,-0.681398,0.063242,0.013298,-1.716890e-17,-0.010780,-3.073938e-17,-5.177687e-17
41,1.200510,-0.738512,-0.101706,0.019678,0.016419,2.856471e-16,0.016847,-4.628839e-16,-4.508902e-16
42,1.015483,0.293800,0.395899,0.452882,0.106689,6.677909e-15,-0.018251,-1.033156e-14,-1.027954e-14
43,1.200510,-0.738512,-0.101706,0.019678,0.016419,2.856471e-16,0.016847,-4.628839e-16,-4.508902e-16
44,0.968626,0.196782,0.113557,-0.122932,-0.090083,-1.155339e-15,-0.238892,-7.694840e-02,7.102141e-02
45,1.200510,-0.738512,-0.101706,0.019678,0.016419,2.856471e-16,0.016847,-4.628839e-16,-4.508902e-16
46,1.058110,0.483952,-0.779677,0.153909,0.070386,-1.716890e-17,0.064510,-3.073938e-17,-5.177687e-17
47,1.200510,-0.738512,-0.101706,0.019678,0.016419,2.856471e-16,0.016847,-4.628839e-16,-4.508902e-16

#### Target table (train and test)

In [54]:
hcpcsevents_pharmacy_label_train = pd.DataFrame()
# Merge data_train with df_pharmacy 

hcpcsevents_pharmacy_label_train = pd.DataFrame(hcpcsevents_data_train['hadm_id']).merge(df_pharmacy, on='hadm_id', how='left')

In [63]:
hcpcsevents_pharmacy_label_train

,hadm_id,23.4% Sodium Chloride,ALPRAZolam,AcetaZOLamide,Acetaminophen,Acetaminophen (Liquid),Acetaminophen IV,Acetaminophen w/Codeine,Acetaminophen-Caff-Butalbital,Acetylcysteine (IV),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,25559382,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,23199774,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,28778757,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,29820177,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,29820177,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,23720373,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,27504040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,25797028,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,25561728,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,29176490,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,22607171,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,26722126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,22999601,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,28676446,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,29654498,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,28543425,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,26739864,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,22896692,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,22380825,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,25166559,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,27494880,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,27962747,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,29654498,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,28778757,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,23143086,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,27504040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,20846853,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,26739864,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,26549334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,29176490,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,24096336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,21039249,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,25559382,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,28477649,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,21039249,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,22502504,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36,27670224,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,20457729,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38,20900955,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,29176490,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,27125816,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
41,26173805,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42,29820177,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43,20282368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,27125816,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
45,22228639,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,22416954,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,28697806,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
hcpcsevents_pharmacy_label_test = pd.DataFrame()
# Merge data_test with df_pharmacy 

hcpcsevents_pharmacy_label_test = pd.DataFrame(hcpcsevents_data_test['hadm_id']).merge(df_pharmacy, on='hadm_id', how='left')

In [66]:
hcpcsevents_pharmacy_label_test

,hadm_id,23.4% Sodium Chloride,ALPRAZolam,AcetaZOLamide,Acetaminophen,Acetaminophen (Liquid),Acetaminophen IV,Acetaminophen w/Codeine,Acetaminophen-Caff-Butalbital,Acetylcysteine (IV),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,29176490,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,27504040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,28676446,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,21390688,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,27504040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,29820177,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,25559382,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,28984460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,28778757,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,25282382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,26332470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,20457729,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,29654498,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [58]:
hcpcsevents_prescriptions_label_train = pd.DataFrame()
# Merge data_train with df_prescriptions

hcpcsevents_prescriptions_label_train = pd.DataFrame(hcpcsevents_data_train['hadm_id']).merge(df_prescriptions, on='hadm_id', how='left')

In [64]:
hcpcsevents_prescriptions_label_train

,hadm_id,*NF* Ertapenem Sodium,0.45% Sodium Chloride,0.83% Sodium Chloride,0.9% NaCl (EXCEL/ViaFLO BAG),0.9% Sodium Chloride,0.9% Sodium Chloride (Mini Bag Plus),23.4% Sodium Chloride,5% Dextrose,5% Dextrose (EXCEL BAG),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,25559382,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,23199774,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,28778757,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,29820177,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,29820177,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,23720373,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,27504040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,25797028,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,25561728,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,29176490,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,22607171,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,26722126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,22999601,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,28676446,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,29654498,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,28543425,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,26739864,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,22896692,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,22380825,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,25166559,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,27494880,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,27962747,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,29654498,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,28778757,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,23143086,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,27504040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,20846853,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,26739864,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,26549334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,29176490,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,24096336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,21039249,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,25559382,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,28477649,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,21039249,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,22502504,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36,27670224,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,20457729,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38,20900955,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,29176490,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,27125816,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
41,26173805,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42,29820177,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43,20282368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,27125816,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
45,22228639,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,22416954,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,28697806,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
hcpcsevents_prescriptions_label_test = pd.DataFrame()
# Merge data_test with df_prescriptions

hcpcsevents_prescriptions_label_test = pd.DataFrame(hcpcsevents_data_test['hadm_id']).merge(df_prescriptions, on='hadm_id', how='left')

In [65]:
hcpcsevents_prescriptions_label_test

,hadm_id,*NF* Ertapenem Sodium,0.45% Sodium Chloride,0.83% Sodium Chloride,0.9% NaCl (EXCEL/ViaFLO BAG),0.9% Sodium Chloride,0.9% Sodium Chloride (Mini Bag Plus),23.4% Sodium Chloride,5% Dextrose,5% Dextrose (EXCEL BAG),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,29176490,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,27504040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,28676446,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,21390688,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,27504040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,29820177,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,25559382,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,28984460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,28778757,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,25282382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,26332470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,20457729,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,29654498,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [67]:
hcpcsevents_pharmacy_label_train.to_csv('hcpcsevents_pharmacy_label_train.csv', index=False)
hcpcsevents_pharmacy_label_test.to_csv('hcpcsevents_pharmacy_label_test.csv', index=False)
hcpcsevents_prescriptions_label_train.to_csv('hcpcsevents_prescriptions_label_train.csv', index=False)
hcpcsevents_prescriptions_label_test.to_csv('hcpcsevents_prescriptions_label_test.csv', index=False)

### labevents

In [ ]:
# Information regarding 252 different admissions

In [85]:
file = "hosp/labevents.csv"
full_path = path + file

df_labevents = pd.read_csv(full_path)

In [86]:
df_labevents['value'] = pd.to_numeric(df_labevents['value'], errors='coerce').fillna(0)

In [87]:
df_labevents.head()

,labevent_id,subject_id,hadm_id,specimen_id,itemid,order_provider_id,charttime,storetime,value,valuenum,valueuom,ref_range_lower,ref_range_upper,flag,priority,comments
0,172061,10014354,29600294.0,1808066,51277,NaN,2148-08-16 00:00:00,2148-08-16 01:30:00,15.40,15.40,%,10.5,15.5,NaN,ROUTINE,NaN
1,172062,10014354,29600294.0,1808066,51279,NaN,2148-08-16 00:00:00,2148-08-16 01:30:00,3.35,3.35,m/uL,4.6,6.1,abnormal,ROUTINE,NaN
2,172068,10014354,29600294.0,1808066,52172,NaN,2148-08-16 00:00:00,2148-08-16 01:30:00,49.70,49.70,fL,35.1,46.3,abnormal,ROUTINE,NaN
3,172063,10014354,29600294.0,1808066,51301,NaN,2148-08-16 00:00:00,2148-08-16 01:30:00,20.30,20.30,K/uL,4.0,10.0,abnormal,ROUTINE,NaN
4,172050,10014354,29600294.0,1808066,51249,NaN,2148-08-16 00:00:00,2148-08-16 01:30:00,31.10,31.10,g/dL,32.0,37.0,abnormal,ROUTINE,NaN

In [88]:
df_labevents['storetime']

0         2148-08-16 01:30:00
1         2148-08-16 01:30:00
2         2148-08-16 01:30:00
3         2148-08-16 01:30:00
4         2148-08-16 01:30:00
                 ...
107722    2116-12-07 19:00:00
107723    2116-12-07 19:00:00
107724    2116-12-07 18:59:00
107725    2116-12-07 18:59:00
107726    2131-05-25 14:36:00
Name: storetime, Length: 107727, dtype: object

Drop: labevent_id, subject_id, order_provider_id (too many Null), charttime, storetime, comments

In [90]:
df_labevents = df_labevents.drop(columns=['labevent_id','subject_id','order_provider_id','charttime','storetime','comments'])

In [91]:
# For flag make abnormal = 1 and fill Null with 0
df_labevents['flag'] = df_labevents['flag'].fillna(0)
df_labevents['flag'] = df_labevents['flag'].replace('abnormal', 1)

In [92]:
# For priority fill Null with N/A and then one hot encode
df_labevents['priority'] = df_labevents['priority'].fillna('N/A')
df_labevents = pd.get_dummies(df_labevents, columns=['priority'])

In [93]:
df_labevents = pd.get_dummies(df_labevents, columns=['valueuom','specimen_id','itemid'])

In [94]:
# Drop any rows with null values 
df_labevents = df_labevents.dropna()
# Reduced from 107727 rows to 66660

#### Split into train and test

In [95]:
data = df_labevents

# Split the dataset into training and testing sets
labevents_data_train, labevents_data_test = train_test_split(data, test_size=0.2, random_state=42)

# Print the shapes of the resulting training and testing sets
print("Training set shape:", labevents_data_train.shape)
print("Testing set shape:", labevents_data_test.shape)

Training set shape: (53328, 11678)
Testing set shape: (13332, 11678)

In [96]:
# uncomment and run if changes are made
path = "C:/Users/jenni/OneDrive/Desktop/IP/"
labevents_data_train.to_csv('labevents_data_train.csv', index=False)
labevents_data_test.to_csv('labevents_data_test.csv', index=False)

#### Dimensionality reduction

In [71]:
file = "labevents_data_train.csv"
full_path = path + file

labevents_data_train = pd.read_csv(full_path)
labevents_data_train

,hadm_id,value,valuenum,ref_range_lower,ref_range_upper,flag,priority_N/A,priority_ROUTINE,priority_STAT,valueuom_,...,itemid_52286,itemid_52312,itemid_52369,itemid_52391,itemid_52419,itemid_52425,itemid_52427,itemid_52769,itemid_52955,itemid_53153
0,26793610.0,19.0,19.0,22.0,32.0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,28998349.0,17.7,17.7,10.5,15.5,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,22490490.0,0.0,134.0,70.0,100.0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,28258130.0,34.0,34.0,35.0,45.0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,22205327.0,2.4,2.4,1.6,2.6,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53323,28872262.0,3.9,3.9,3.3,5.1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
53324,21476294.0,100.0,100.0,96.0,108.0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
53325,26467376.0,68.5,68.5,9.4,12.5,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
53326,21476294.0,0.0,0.0,0.0,0.0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
53327,29276678.0,0.0,0.0,0.0,0.0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Need to reduce from 11681 to 10665
# Actually I'm just going to leave it because that would be so intensive

In [ ]:
# Note that I would be surprised if this performed well at all

#### Target table (train and test)

In [72]:
labevents_pharmacy_label_train = pd.DataFrame()
# Merge data_train with df_pharmacy 

labevents_pharmacy_label_train = pd.DataFrame(labevents_data_train['hadm_id']).merge(df_pharmacy, on='hadm_id', how='left')

In [73]:
labevents_pharmacy_label_train

,hadm_id,23.4% Sodium Chloride,ALPRAZolam,AcetaZOLamide,Acetaminophen,Acetaminophen (Liquid),Acetaminophen IV,Acetaminophen w/Codeine,Acetaminophen-Caff-Butalbital,Acetylcysteine (IV),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,26793610.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,28998349.0,0.0,0.0,4.0,1.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,22490490.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,28258130.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,22205327.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53323,28872262.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53324,21476294.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53325,26467376.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53326,21476294.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53327,29276678.0,0.0,0.0,0.0,7.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0

In [74]:
file = "labevents_data_test.csv"
full_path = path + file

labevents_data_test = pd.read_csv(full_path)

labevents_pharmacy_label_test = pd.DataFrame()
# Merge data_test with df_pharmacy 

labevents_pharmacy_label_test = pd.DataFrame(labevents_data_test['hadm_id']).merge(df_pharmacy, on='hadm_id', how='left')

In [75]:
labevents_pharmacy_label_test

,hadm_id,23.4% Sodium Chloride,ALPRAZolam,AcetaZOLamide,Acetaminophen,Acetaminophen (Liquid),Acetaminophen IV,Acetaminophen w/Codeine,Acetaminophen-Caff-Butalbital,Acetylcysteine (IV),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,27993466.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,26275841.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,26369609.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,26369609.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,21476294.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13327,23559586.0,0.0,0.0,0.0,2.0,1.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13328,22390287.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13329,21457723.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13330,21476294.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13331,29488258.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [76]:
labevents_prescriptions_label_train = pd.DataFrame()
# Merge data_train with df_prescriptions

labevents_prescriptions_label_train = pd.DataFrame(labevents_data_train['hadm_id']).merge(df_prescriptions, on='hadm_id', how='left')

In [77]:
labevents_prescriptions_label_train

,hadm_id,*NF* Ertapenem Sodium,0.45% Sodium Chloride,0.83% Sodium Chloride,0.9% NaCl (EXCEL/ViaFLO BAG),0.9% Sodium Chloride,0.9% Sodium Chloride (Mini Bag Plus),23.4% Sodium Chloride,5% Dextrose,5% Dextrose (EXCEL BAG),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,26793610.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,28998349.0,0.0,0.0,0.0,0.0,19.0,0.0,0.0,18.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,22490490.0,0.0,2.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,28258130.0,0.0,0.0,0.0,0.0,22.0,8.0,0.0,22.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,22205327.0,0.0,0.0,0.0,0.0,15.0,2.0,0.0,10.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53323,28872262.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,15.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53324,21476294.0,0.0,0.0,0.0,0.0,9.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53325,26467376.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53326,21476294.0,0.0,0.0,0.0,0.0,9.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53327,29276678.0,0.0,0.0,0.0,0.0,34.0,9.0,0.0,16.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0

In [78]:
labevents_prescriptions_label_test = pd.DataFrame()
# Merge data_test with df_prescriptions

labevents_prescriptions_label_test = pd.DataFrame(labevents_data_test['hadm_id']).merge(df_prescriptions, on='hadm_id', how='left')

In [79]:
labevents_prescriptions_label_test

,hadm_id,*NF* Ertapenem Sodium,0.45% Sodium Chloride,0.83% Sodium Chloride,0.9% NaCl (EXCEL/ViaFLO BAG),0.9% Sodium Chloride,0.9% Sodium Chloride (Mini Bag Plus),23.4% Sodium Chloride,5% Dextrose,5% Dextrose (EXCEL BAG),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,27993466.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,26275841.0,0.0,0.0,0.0,0.0,5.0,2.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,26369609.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,26369609.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,21476294.0,0.0,0.0,0.0,0.0,9.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13327,23559586.0,0.0,0.0,0.0,0.0,8.0,3.0,0.0,17.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13328,22390287.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13329,21457723.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13330,21476294.0,0.0,0.0,0.0,0.0,9.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13331,29488258.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [80]:
labevents_pharmacy_label_train.to_csv('labevents_pharmacy_label_train.csv', index=False)
labevents_pharmacy_label_test.to_csv('labevents_pharmacy_label_test.csv', index=False)
labevents_prescriptions_label_train.to_csv('labevents_prescriptions_label_train.csv', index=False)
labevents_prescriptions_label_test.to_csv('labevents_prescriptions_label_test.csv', index=False)

### microbiologyevents

In [97]:
file = "hosp/microbiologyevents.csv"
full_path = path + file

df_microbio = pd.read_csv(full_path)

In [98]:
df_microbio.head(5)

,microevent_id,subject_id,hadm_id,micro_specimen_id,order_provider_id,chartdate,charttime,spec_itemid,spec_type_desc,test_seq,...,org_name,isolate_num,quantity,ab_itemid,ab_name,dilution_text,dilution_comparison,dilution_value,interpretation,comments
0,36,10000032,25742920.0,7814634,NaN,2180-08-06 00:00:00,2180-08-06 20:35:00,70070,SWAB,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No VRE isolated.
1,15,10000032,22595853.0,5717063,NaN,2180-05-07 00:00:00,2180-05-07 00:19:00,70070,SWAB,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No VRE isolated.
2,32,10000032,29079034.0,5901894,NaN,2180-07-24 00:00:00,2180-07-24 00:55:00,70070,SWAB,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No VRE isolated.
3,7013,10020944,29974575.0,4646730,NaN,2131-02-27 00:00:00,2131-02-27 17:41:00,70070,SWAB,1,...,ENTEROCOCCUS SP.,1.0,NaN,90015.0,VANCOMYCIN,>256,NaN,NaN,R,NaN
4,12898,10037975,27617929.0,1636367,NaN,2185-01-17 00:00:00,2185-01-17 21:32:00,70070,SWAB,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No VRE isolated.

Drop: microevent_id, subject_id, chartdate, charttime, test_seq, storedate, storetime, test_name and org_itemid (since info in name), quantity, ab_name, comments, micro_specimen_id (unique identifier for sample as some measurements are made on the same sample)
Keep but categorical: order_provider_id, spec_type_desc, dilution_text, dilution_comparison
Impute null with 0: order_provider_id, org_itemid, isolate_num, ab_itemid, dilution_value
Impute with N/A and then one hot encode: interpretation

In [99]:
# Drop
# spec_itemid , test_itemid
df_microbio = df_microbio.drop(columns=['microevent_id','subject_id','chartdate','charttime','test_seq','storedate',
                                       'storetime','quantity','comments','ab_itemid',
                                       'spec_itemid','test_itemid','org_itemid','micro_specimen_id'])

In [100]:
# Impute null with 0: order_provider_id, org_itemid, isolate_num, ab_itemid, dilution_value
df_microbio['order_provider_id'] = df_microbio['order_provider_id'].fillna(0)
df_microbio['isolate_num'] = df_microbio['isolate_num'].fillna(0)
df_microbio['dilution_value'] = df_microbio['dilution_value'].fillna(0)

In [101]:
# Impute with N/A and then one hot encode: interpretation
# encode test_name, ab_name

df_microbio['interpretation'] = df_microbio['interpretation'].fillna('N/A')
df_microbio['test_name'] = df_microbio['test_name'].fillna('N/A')
df_microbio['ab_name'] = df_microbio['ab_name'].fillna('N/A')
df_microbio['org_name'] = df_microbio['org_name'].fillna('None')
df_microbio = pd.get_dummies(df_microbio, columns=['org_name','interpretation','ab_name','test_name'])

In [102]:
# Keep but categorical: order_provider_id, spec_type_desc, dilution_text, dilution_comparison
df_microbio = pd.get_dummies(df_microbio, columns=['order_provider_id','spec_type_desc','dilution_text',
                                                  'dilution_comparison'])

In [103]:
df_microbio = df_microbio.dropna()

In [104]:
df_microbio

,hadm_id,isolate_num,dilution_value,org_name_ABIOTROPHIA/GRANULICATELLA SPECIES,org_name_ACINETOBACTER BAUMANNII,org_name_ACINETOBACTER BAUMANNII COMPLEX,org_name_ANAEROBIC GRAM POSITIVE COCCUS(I),org_name_ANAEROBIC GRAM POSITIVE ROD(S),org_name_BACTEROIDES FRAGILIS GROUP,org_name_BETA STREPTOCOCCUS GROUP A,...,dilution_text_=>128,dilution_text_=>16,dilution_text_=>32,dilution_text_=>4,dilution_text_=>64,dilution_text_=>8,dilution_text_>256,dilution_comparison_<=,dilution_comparison_=,dilution_comparison_=>
0,25742920.0,0.0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,22595853.0,0.0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,29079034.0,0.0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,29974575.0,1.0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,27617929.0,0.0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2893,29600294.0,0.0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2894,28506150.0,0.0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2895,25508812.0,0.0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2897,22413744.0,0.0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2898,23721604.0,1.0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

#### Split into train and test

In [105]:
data = df_microbio

# Split the dataset into training and testing sets
microbio_data_train, microbio_data_test = train_test_split(data, test_size=0.2, random_state=42)

# Print the shapes of the resulting training and testing sets
print("Training set shape:", microbio_data_train.shape)
print("Testing set shape:", microbio_data_test.shape)

Training set shape: (1542, 276)
Testing set shape: (386, 276)

In [106]:
# # uncomment and run if changes are made

# microbio_data_train.to_csv('microbio_data_train.csv', index=False)
# microbio_data_test.to_csv('microbio_data_test.csv', index=False)

In [82]:
file = "microbio_data_train.csv"
full_path = path + file

microbio_data_train = pd.read_csv(full_path)

microbio_data_train

,hadm_id,isolate_num,dilution_value,org_name_ABIOTROPHIA/GRANULICATELLA SPECIES,org_name_ACINETOBACTER BAUMANNII,org_name_ACINETOBACTER BAUMANNII COMPLEX,org_name_ANAEROBIC GRAM POSITIVE COCCUS(I),org_name_ANAEROBIC GRAM POSITIVE ROD(S),org_name_BACTEROIDES FRAGILIS GROUP,org_name_BETA STREPTOCOCCUS GROUP A,...,dilution_text_=>128,dilution_text_=>16,dilution_text_=>32,dilution_text_=>4,dilution_text_=>64,dilution_text_=>8,dilution_text_>256,dilution_comparison_<=,dilution_comparison_=,dilution_comparison_=>
0,24256866.0,1.0,1.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,25926192.0,0.0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,29079034.0,0.0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,22205327.0,1.0,1.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,24982426.0,1.0,1.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1537,28613200.0,1.0,0.5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1538,22130791.0,0.0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1539,28998349.0,0.0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1540,29366372.0,0.0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1541,23300884.0,1.0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

#### Dimensionality reduction

In [ ]:
# Fine

#### Target table (train and test)

In [83]:
microbio_pharmacy_label_train = pd.DataFrame()
# Merge data_train with df_pharmacy 

microbio_pharmacy_label_train = pd.DataFrame(microbio_data_train['hadm_id']).merge(df_pharmacy, on='hadm_id', how='left')

In [84]:
microbio_pharmacy_label_train

,hadm_id,23.4% Sodium Chloride,ALPRAZolam,AcetaZOLamide,Acetaminophen,Acetaminophen (Liquid),Acetaminophen IV,Acetaminophen w/Codeine,Acetaminophen-Caff-Butalbital,Acetylcysteine (IV),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,24256866.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,25926192.0,0.0,0.0,0.0,4.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,29079034.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,22205327.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,24982426.0,0.0,0.0,0.0,2.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1537,28613200.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1538,22130791.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1539,28998349.0,0.0,0.0,4.0,1.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1540,29366372.0,0.0,0.0,0.0,4.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1541,23300884.0,0.0,0.0,0.0,5.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [85]:
file = "microbio_data_test.csv"
full_path = path + file

microbio_data_test = pd.read_csv(full_path)

microbio_pharmacy_label_test = pd.DataFrame()
# Merge data_test with df_pharmacy 

microbio_pharmacy_label_test = pd.DataFrame(microbio_data_test['hadm_id']).merge(df_pharmacy, on='hadm_id', how='left')

In [86]:
microbio_pharmacy_label_test

,hadm_id,23.4% Sodium Chloride,ALPRAZolam,AcetaZOLamide,Acetaminophen,Acetaminophen (Liquid),Acetaminophen IV,Acetaminophen w/Codeine,Acetaminophen-Caff-Butalbital,Acetylcysteine (IV),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,27996267.0,0.0,0.0,0.0,12.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,27411876.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,27738145.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,25020332.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,23473524.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
381,27189241.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
382,22987108.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
383,28613200.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
384,28477357.0,0.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
385,28258130.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [87]:
microbio_prescriptions_label_train = pd.DataFrame()
# Merge data_train with df_prescriptions

microbio_prescriptions_label_train = pd.DataFrame(microbio_data_train['hadm_id']).merge(df_prescriptions, on='hadm_id', how='left')

In [88]:
microbio_prescriptions_label_train

,hadm_id,*NF* Ertapenem Sodium,0.45% Sodium Chloride,0.83% Sodium Chloride,0.9% NaCl (EXCEL/ViaFLO BAG),0.9% Sodium Chloride,0.9% Sodium Chloride (Mini Bag Plus),23.4% Sodium Chloride,5% Dextrose,5% Dextrose (EXCEL BAG),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,24256866.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,25926192.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,7.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,29079034.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,22205327.0,0.0,0.0,0.0,0.0,15.0,2.0,0.0,10.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,24982426.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1537,28613200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1538,22130791.0,0.0,0.0,0.0,0.0,13.0,2.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1539,28998349.0,0.0,0.0,0.0,0.0,19.0,0.0,0.0,18.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1540,29366372.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1541,23300884.0,0.0,0.0,0.0,0.0,3.0,2.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [89]:
microbio_prescriptions_label_test = pd.DataFrame()
# Merge data_test with df_prescriptions

microbio_prescriptions_label_test = pd.DataFrame(microbio_data_test['hadm_id']).merge(df_prescriptions, on='hadm_id', how='left')

In [90]:
microbio_prescriptions_label_test

,hadm_id,*NF* Ertapenem Sodium,0.45% Sodium Chloride,0.83% Sodium Chloride,0.9% NaCl (EXCEL/ViaFLO BAG),0.9% Sodium Chloride,0.9% Sodium Chloride (Mini Bag Plus),23.4% Sodium Chloride,5% Dextrose,5% Dextrose (EXCEL BAG),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,27996267.0,0.0,0.0,0.0,0.0,7.0,2.0,0.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,27411876.0,0.0,0.0,4.0,0.0,5.0,0.0,0.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,27738145.0,0.0,0.0,0.0,0.0,11.0,5.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,25020332.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,23473524.0,0.0,0.0,0.0,0.0,4.0,6.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
381,27189241.0,0.0,0.0,0.0,0.0,3.0,3.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
382,22987108.0,0.0,0.0,0.0,0.0,18.0,17.0,0.0,10.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
383,28613200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
384,28477357.0,0.0,1.0,0.0,0.0,7.0,4.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
385,28258130.0,0.0,0.0,0.0,0.0,22.0,8.0,0.0,22.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [91]:
microbio_pharmacy_label_train.to_csv('microbio_pharmacy_label_train.csv', index=False)
microbio_pharmacy_label_test.to_csv('microbio_pharmacy_label_test.csv', index=False)
microbio_prescriptions_label_train.to_csv('microbio_prescriptions_label_train.csv', index=False)
microbio_prescriptions_label_test.to_csv('microbio_prescriptions_label_test.csv', index=False)

### patients

Could have added patient age to a miscellaneous patient info table which maps each hadm_id to data about that patient
But not enough valuable data to do that
Highly unlikely that information about the person themselves is enough to predict any medication

In [37]:
df_patients.head()

   subject_id gender  anchor_age  anchor_year anchor_year_group         dod
0    10014729      F          21         2125       2011 - 2013         NaN
1    10003400      F          72         2134       2011 - 2013  2137-09-02
2    10002428      F          80         2155       2011 - 2013         NaN
3    10032725      F          38         2143       2011 - 2013  2143-03-30
4    10027445      F          48         2142       2011 - 2013  2146-02-09

### poe

provider order entry, orders of treatments and procedures 

Not relevant enough to prescriptions

### procedures_icd

Use icd_code and make days_since_admission of procedure as another feature 
But an admission has up to 23 associated procedures, 352 different ones means adding that many one hot encoded features

In [93]:
file = "hosp/procedures_icd.csv"
full_path = path + file

df_procedures = pd.read_csv(full_path)

In [94]:
df_procedures

     subject_id   hadm_id  seq_num   chartdate icd_code  icd_version
0      10011398  27505812        3  2146-12-15     3961            9
1      10011398  27505812        2  2146-12-15     3615            9
2      10011398  27505812        1  2146-12-15     3614            9
3      10014729  23300884        4  2125-03-23     3897            9
4      10014729  23300884        1  2125-03-20     3403            9
..          ...       ...      ...         ...      ...          ...
717    10004733  27411876        3  2174-12-20     4513            9
718    10021118  24490144        4  2161-11-19  5A1221Z           10
719    10021118  24490144        3  2161-11-19  06BP4ZZ           10
720    10021118  24490144        1  2161-11-19  02100Z9           10
721    10021118  24490144        2  2161-11-19  02110Z3           10

[722 rows x 6 columns]

Drop: subject_id, chartdate
Encode: icd_code

In [95]:
# make a feature called days_since_admission of chartdate - admitdate

# Convert to datetime
df_procedures['chartdate'] = pd.to_datetime(df_procedures['chartdate'], format='%Y-%m-%d')

# Add admittime column from other dataframe
df_procedures = df_procedures.merge(df_admittime, on='hadm_id', how='left')

# # Discard the time part and keep only the date
df_procedures['admittime'] = df_procedures['admittime'].dt.date
df_procedures['chartdate'] = df_procedures['chartdate'].dt.date

df_procedures['days_since_admission'] = df_procedures['chartdate'] - df_procedures['admittime']

# Fill any non time values
df_procedures['days_since_admission'] = df_procedures['days_since_admission'].fillna(pd.Timedelta(0))

# Drop the admission time column
df_procedures = df_procedures.drop(columns=['admittime'])

In [96]:
# Drop 
df_procedures = df_procedures.drop(columns=['subject_id','chartdate','seq_num','icd_version'])

In [97]:
# Encode
df_procedures = pd.get_dummies(df_procedures, columns=['icd_code'])

In [98]:
df_procedures

,hadm_id,days_since_admission,icd_code_0039,icd_code_0040,icd_code_0041,icd_code_0045,icd_code_0051,icd_code_0066,icd_code_0069,icd_code_0091,...,icd_code_B41GYZZ,icd_code_B518YZA,icd_code_B51W1ZZ,icd_code_B543ZZ3,icd_code_B548ZZA,icd_code_B54BZZA,icd_code_BT1DYZZ,icd_code_BT1FYZZ,icd_code_D7021ZZ,icd_code_DW021ZZ
0,27505812,0 days,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,27505812,0 days,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,27505812,0 days,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,23300884,4 days,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,23300884,1 days,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
717,27411876,16 days,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
718,24490144,4 days,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
719,24490144,4 days,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
720,24490144,4 days,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
721,24490144,4 days,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

#### Split into train and test

In [99]:
data = df_procedures

# Split the dataset into training and testing sets
procedures_data_train, procedures_data_test = train_test_split(data, test_size=0.2, random_state=42)

# Print the shapes of the resulting training and testing sets
print("Training set shape:", procedures_data_train.shape)
print("Testing set shape:", procedures_data_test.shape)

Training set shape: (577, 354)
Testing set shape: (145, 354)

In [102]:
# # uncomment and run if changes are made
# path = "C:/Users/jenni/OneDrive/Desktop/IP/"
# procedures_data_train.to_csv('procedures_data_train.csv', index=False)
# procedures_data_test.to_csv('procedures_data_test.csv', index=False)

#### Dimensionality reduction

In [ ]:
# Need to reduce from 354 to 115

In [102]:
# drop admittime and convert days into float
procedures_data_train = procedures_data_train.drop(columns=['hadm_id'])
# hcpcsevents_data_train['days_since_admission'] = hcpcsevents_data_train['days_since_admission'].apply(convert_to_days)
procedures_data_test = procedures_data_test.drop(columns=['hadm_id'])
# hcpcsevents_data_test['days_since_admission'] = hcpcsevents_data_test['days_since_admission'].apply(convert_to_days)

procedures_data_train['days_since_admission'] = procedures_data_train['days_since_admission'].astype(str)
procedures_data_train['days_since_admission'] = procedures_data_train['days_since_admission'].str.split().str[0].astype(int)
procedures_data_test['days_since_admission'] = procedures_data_test['days_since_admission'].astype(str)
procedures_data_test['days_since_admission'] = procedures_data_test['days_since_admission'].str.split().str[0].astype(int)

In [103]:
from sklearn.decomposition import TruncatedSVD

# Number of desired features (components)
n_components = 115

# Initialize Truncated SVD with the desired number of components
svd = TruncatedSVD(n_components=n_components)

# Fit the Truncated SVD model to the sparse matrix and transform the data
svd.fit(procedures_data_train)
procedures_data_train = svd.transform(procedures_data_train)

# Get the explained variance ratio (how much variance is explained by each component)
explained_variance_ratio = svd.explained_variance_ratio_

# Print the transformed matrix and explained variance ratio
# print("Transformed Matrix:")
# print(transformed_matrix)
print("\nExplained Variance Ratio:")
print(explained_variance_ratio)

print("\n Amount of original variance conserved:", np.sum(svd.explained_variance_ratio_))

Explained Variance Ratio:
[9.73194594e-01 9.63956768e-04 8.67098052e-04 6.90062211e-04
 5.54668800e-04 4.22187644e-04 4.22154762e-04 4.20757510e-04
 4.05733127e-04 3.75417355e-04 3.73259131e-04 3.63226152e-04
 2.76477634e-04 2.77845065e-04 2.80370757e-04 2.79764891e-04
 2.80624870e-04 2.80822912e-04 2.41167874e-04 2.33702941e-04
 2.33252330e-04 2.33869101e-04 2.34628736e-04 2.32896142e-04
 2.22454352e-04 1.87139296e-04 1.87464627e-04 1.87346080e-04
 1.87707001e-04 1.85972237e-04 1.79739518e-04 1.39082549e-04
 1.40633212e-04 1.40734017e-04 1.39821221e-04 1.39564765e-04
 1.39843238e-04 1.40572097e-04 1.40746832e-04 1.40611550e-04
 1.40479559e-04 1.40152263e-04 1.40536626e-04 1.40296280e-04
 1.40432891e-04 1.40701066e-04 1.40566590e-04 1.22340989e-04
 9.36608088e-05 9.32775339e-05 9.34782545e-05 9.37598472e-05
 9.28048813e-05 9.35719607e-05 9.38445869e-05 9.38183034e-05
 9.32649522e-05 9.35327910e-05 9.38063105e-05 9.38187813e-05
 9.38256900e-05 9.34729786e-05 9.38128148e-05 9.38234211e-05
 9.38257055e-05 9.37072222e-05 9.32035267e-05 9.36988955e-05
 9.37233769e-05 9.38244398e-05 9.38213293e-05 9.37002624e-05
 9.36651944e-05 9.38085452e-05 9.37621905e-05 9.37277448e-05
 9.32686564e-05 9.37934256e-05 9.37911671e-05 9.36874458e-05
 9.35927397e-05 9.34504223e-05 9.37075975e-05 9.37422640e-05
 9.36483075e-05 9.37127402e-05 9.37018745e-05 9.35741990e-05
 9.31222380e-05 9.29900212e-05 9.35329758e-05 7.80552961e-05
 4.69008412e-05 4.69175799e-05 4.69252726e-05 4.69216680e-05
 4.68724619e-05 4.66865918e-05 4.66502879e-05 4.68603660e-05
 4.68958518e-05 4.69255293e-05 4.65968137e-05 4.69241813e-05
 4.68439342e-05 4.68798686e-05 4.68905446e-05 4.68880531e-05
 4.69157275e-05 4.69136059e-05 4.68707473e-05 4.69159955e-05
 4.68936255e-05 4.67544543e-05 4.68578388e-05]

 Amount of original variance conserved: 0.9910245930148194

In [104]:
procedures_data_test = svd.transform(procedures_data_test)

In [105]:
# # uncomment and run if changes are made
path = "C:/Users/jenni/OneDrive/Desktop/IP/"
pd.DataFrame(hcpcsevents_data_train).to_csv('procedures_data_train.csv', index=False)
pd.DataFrame(hcpcsevents_data_test).to_csv('procedures_data_test.csv', index=False)

In [106]:
pd.DataFrame(procedures_data_train)

,0,1,2,3,4,5,6,7,8,9,...,105,106,107,108,109,110,111,112,113,114
0,2.000059e+00,-4.996919e-03,-6.176807e-03,-3.091150e-03,-2.939515e-03,3.265197e-08,4.779881e-09,1.098042e-07,-5.147800e-03,8.791766e-08,...,1.723991e-16,-6.920090e-17,-1.264648e-16,-2.252909e-16,-2.254744e-16,-2.653788e-16,-3.404281e-17,-5.331326e-17,1.389538e-16,1.517257e-16
1,4.999895e+00,-1.158314e-02,-1.419414e-02,-6.941209e-03,-6.409126e-03,6.667061e-07,4.830000e-07,-4.823768e-07,-1.062209e-02,-4.207601e-07,...,-1.421846e-01,2.134625e-02,-1.561037e-01,1.316330e-02,8.808895e-02,-7.181389e-02,-5.037107e-02,-2.705678e-02,-3.370400e-02,-7.375045e-02
2,-3.640819e-28,-3.068616e-09,7.271573e-09,-2.288517e-08,-4.180636e-08,-4.373477e-07,-3.625336e-07,9.954627e-08,-3.405618e-07,1.249714e-07,...,3.592073e-02,-7.048373e-02,-2.598547e-02,-1.078308e-01,-9.545971e-02,-2.900393e-02,-7.492540e-02,-7.954976e-02,-1.703582e-02,-6.226183e-03
3,4.000017e+00,-9.642018e-03,-1.187252e-02,-5.882008e-03,-5.524707e-03,-3.239198e-08,-3.778340e-09,2.142482e-07,-9.467094e-03,2.266207e-07,...,1.826016e-16,-3.952256e-17,4.186505e-17,-1.470594e-16,1.439083e-17,2.955801e-17,-5.670150e-17,1.283607e-16,1.148436e-16,1.412548e-16
4,1.585435e-03,-1.177206e-02,-1.868831e-02,-2.070534e-02,9.978812e-01,-8.742895e-11,-4.109783e-09,-1.953466e-09,2.784239e-02,-6.178584e-09,...,-2.151057e-16,-4.891920e-16,-6.158268e-17,-3.885781e-16,-9.887924e-17,3.469447e-17,-1.665335e-16,0.000000e+00,1.734723e-16,-1.700029e-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
572,2.200045e+01,-5.458522e-02,-6.748131e-02,-3.381285e-02,-3.227299e-02,-1.522658e-09,-2.257021e-08,6.424285e-09,-5.729363e-02,-1.339073e-08,...,-5.734025e-18,2.002606e-16,1.661575e-17,3.095006e-16,6.941699e-18,-6.207761e-17,1.032285e-16,-2.711454e-18,-8.133143e-17,2.022745e-16
573,1.199975e+01,-2.779953e-02,-3.406595e-02,-1.665895e-02,-1.538171e-02,1.161905e-07,1.328911e-07,1.432061e-07,-2.549233e-02,2.680592e-07,...,4.438877e-02,-4.147574e-02,3.201825e-02,-3.476194e-02,-2.977392e-02,-8.405603e-02,1.827922e-02,2.589685e-02,-4.825090e-02,2.862856e-02
574,4.000051e+00,-9.759292e-03,-1.203289e-02,-5.982101e-03,-5.642806e-03,-2.872741e-08,-3.519828e-09,8.779779e-08,-9.743302e-03,9.175559e-08,...,-2.296315e-17,-1.947803e-16,1.477916e-16,-1.660872e-16,-1.924749e-16,1.741495e-17,2.077354e-16,4.082497e-17,7.125869e-17,1.982421e-17
575,2.969375e-03,9.930239e-01,1.055282e-01,1.881100e-02,1.141382e-02,-9.937699e-11,-4.062784e-09,-1.990630e-09,1.360885e-02,-6.131220e-09,...,-2.084921e-16,-5.128276e-16,-7.285839e-17,-3.955170e-16,-1.196959e-16,1.006140e-16,-1.249001e-16,1.561251e-17,2.159731e-16,-1.721713e-16
576,1.000080e+00,-2.674369e-03,-3.328948e-03,-1.695727e-03,-1.646892e-03,1.029041e-07,-4.061652e-08,7.426141e-08,-2.988147e-03,8.228420e-08,...,-1.124263e-16,-8.252219e-17,3.727316e-17,-2.145605e-16,7.873292e-17,1.099550e-16,-1.367173e-16,3.189029e-17,3.560315e-16,-8.503273e-17

#### Target table (train and test)

In [103]:
procedures_pharmacy_label_train = pd.DataFrame()
# Merge data_train with df_pharmacy 

procedures_pharmacy_label_train = pd.DataFrame(procedures_data_train['hadm_id']).merge(df_pharmacy, on='hadm_id', how='left')

In [104]:
procedures_pharmacy_label_train

,hadm_id,23.4% Sodium Chloride,ALPRAZolam,AcetaZOLamide,Acetaminophen,Acetaminophen (Liquid),Acetaminophen IV,Acetaminophen w/Codeine,Acetaminophen-Caff-Butalbital,Acetylcysteine (IV),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,22130791,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,23300884,0.0,0.0,0.0,5.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,29374560,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,27189241,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,26275841,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
572,21027282,0.0,0.0,0.0,2.0,1.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
573,20755971,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
574,25103777,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
575,20385771,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
576,24982426,0.0,0.0,0.0,2.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [105]:
procedures_pharmacy_label_test = pd.DataFrame()
# Merge data_test with df_pharmacy 

procedures_pharmacy_label_test = pd.DataFrame(procedures_data_test['hadm_id']).merge(df_pharmacy, on='hadm_id', how='left')

In [106]:
procedures_pharmacy_label_test

,hadm_id,23.4% Sodium Chloride,ALPRAZolam,AcetaZOLamide,Acetaminophen,Acetaminophen (Liquid),Acetaminophen IV,Acetaminophen w/Codeine,Acetaminophen-Caff-Butalbital,Acetylcysteine (IV),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,23403708,0,0,0,4,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,27738145,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,20214994,0,0,0,2,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,22987108,0,0,0,3,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,28324362,0,0,0,3,0,4,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,28258130,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
141,23403708,0,0,0,4,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
142,28258130,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
143,21599196,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
144,28166872,0,0,0,0,3,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [107]:
procedures_prescriptions_label_train = pd.DataFrame()
# Merge data_train with df_prescriptions

procedures_prescriptions_label_train = pd.DataFrame(procedures_data_train['hadm_id']).merge(df_prescriptions, on='hadm_id', how='left')

In [108]:
procedures_prescriptions_label_train

,hadm_id,*NF* Ertapenem Sodium,0.45% Sodium Chloride,0.83% Sodium Chloride,0.9% NaCl (EXCEL/ViaFLO BAG),0.9% Sodium Chloride,0.9% Sodium Chloride (Mini Bag Plus),23.4% Sodium Chloride,5% Dextrose,5% Dextrose (EXCEL BAG),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,22130791,0.0,0.0,0.0,0.0,13.0,2.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,23300884,0.0,0.0,0.0,0.0,3.0,2.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,29374560,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,27189241,0.0,0.0,0.0,0.0,3.0,3.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,26275841,0.0,0.0,0.0,0.0,5.0,2.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
572,21027282,0.0,0.0,0.0,0.0,10.0,1.0,0.0,17.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
573,20755971,0.0,0.0,0.0,0.0,2.0,6.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
574,25103777,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
575,20385771,0.0,0.0,0.0,0.0,10.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
576,24982426,0.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [109]:
procedures_prescriptions_label_test = pd.DataFrame()
# Merge data_test with df_prescriptions

procedures_prescriptions_label_test = pd.DataFrame(procedures_data_test['hadm_id']).merge(df_prescriptions, on='hadm_id', how='left')

In [110]:
procedures_prescriptions_label_test

,hadm_id,*NF* Ertapenem Sodium,0.45% Sodium Chloride,0.83% Sodium Chloride,0.9% NaCl (EXCEL/ViaFLO BAG),0.9% Sodium Chloride,0.9% Sodium Chloride (Mini Bag Plus),23.4% Sodium Chloride,5% Dextrose,5% Dextrose (EXCEL BAG),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,23403708,0,0,0,0,1,0,0,2,0,...,0,0,0,0,0,0,0,0,0,0
1,27738145,0,0,0,0,11,5,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,20214994,0,0,0,0,4,2,0,11,5,...,0,0,0,0,0,0,0,0,0,0
3,22987108,0,0,0,0,18,17,0,10,5,...,0,0,0,0,0,0,1,0,0,0
4,28324362,0,0,0,0,2,0,0,2,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,28258130,0,0,0,0,22,8,0,22,0,...,0,0,0,0,0,0,1,0,0,0
141,23403708,0,0,0,0,1,0,0,2,0,...,0,0,0,0,0,0,0,0,0,0
142,28258130,0,0,0,0,22,8,0,22,0,...,0,0,0,0,0,0,1,0,0,0
143,21599196,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
144,28166872,0,2,2,0,7,4,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [111]:
procedures_pharmacy_label_train.to_csv('procedures_pharmacy_label_train.csv', index=False)
procedures_pharmacy_label_test.to_csv('procedures_pharmacy_label_test.csv', index=False)
procedures_prescriptions_label_train.to_csv('procedures_prescriptions_label_train.csv', index=False)
procedures_prescriptions_label_test.to_csv('procedures_prescriptions_label_test.csv', index=False)

### services

Unit taking care of the patient is not useful for prescribing

### transfers

Same as above

### chartevents

In [20]:
file = "icu/chartevents.csv"
full_path = path + file

df_chart = pd.read_csv(full_path)

In [21]:
df_chart.head()

,subject_id,hadm_id,stay_id,caregiver_id,charttime,storetime,itemid,value,valuenum,valueuom,warning
0,10005817,20626031,32604416,6770.0,2132-12-16 00:00:00,2132-12-15 23:45:00,225054,On,NaN,NaN,0.0
1,10005817,20626031,32604416,6770.0,2132-12-16 00:00:00,2132-12-15 23:43:00,223769,100,100.0,%,0.0
2,10005817,20626031,32604416,6770.0,2132-12-16 00:00:00,2132-12-15 23:47:00,223956,Atrial demand,NaN,NaN,0.0
3,10005817,20626031,32604416,6770.0,2132-12-16 00:00:00,2132-12-15 23:47:00,224866,Yes,NaN,NaN,0.0
4,10005817,20626031,32604416,6770.0,2132-12-16 00:00:00,2132-12-15 23:45:00,227341,No,0.0,NaN,0.0

Drop: subject_id, charttime, storetime, stay_id, caregiver_id (the person who documented the data)
Encode: value,itemid
Impute with 0: valuenum, warning
Impute with N/A and encode: valueuom

In [22]:
# Drop 
df_chart = df_chart.drop(columns=['subject_id','charttime','storetime', 'stay_id','caregiver_id'])

In [23]:
# Impute with N/A and encode
df_chart['valueuom'] = df_chart['valueuom'].fillna('N/A')
df_chart = pd.get_dummies(df_chart, columns=['valueuom','value','itemid'])

In [24]:
# Impute with 0
df_chart['valuenum'] = df_chart['valuenum'].fillna(0)
df_chart['warning'] = df_chart['warning'].fillna(0)

#### Split into train and test

In [25]:
data = df_chart

# Split the dataset into training and testing sets
chart_data_train, chart_data_test = train_test_split(data, test_size=0.2, random_state=42)

# Print the shapes of the resulting training and testing sets
print("Training set shape:", chart_data_train.shape)
print("Testing set shape:", chart_data_test.shape)

Training set shape: (535089, 5607)
Testing set shape: (133773, 5607)

In [127]:
# # uncomment and run if changes are made

# chart_data_train.to_csv('chart_data_train.csv', index=False)
# chart_data_test.to_csv('chart_data_test.csv', index=False)

In [26]:
# path = "C:/Users/jenni/OneDrive/Desktop/IP/"
# file = "chart_data_train.csv"
# full_path = path + file

# chart_data_train = pd.read_csv(full_path)

# chart_data_train

#### Dimensionality reduction

In [ ]:
# Fine

#### Target table (train and test)

In [27]:
chart_pharmacy_label_train = pd.DataFrame()
# Merge data_train with df_pharmacy 

chart_pharmacy_label_train = pd.DataFrame(chart_data_train['hadm_id']).merge(df_pharmacy, on='hadm_id', how='left')

In [28]:
chart_pharmacy_label_train

,hadm_id,23.4% Sodium Chloride,ALPRAZolam,AcetaZOLamide,Acetaminophen,Acetaminophen (Liquid),Acetaminophen IV,Acetaminophen w/Codeine,Acetaminophen-Caff-Butalbital,Acetylcysteine (IV),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,20626031,0.0,0.0,0.0,4.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,25926192,0.0,0.0,0.0,4.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,29295881,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,28662225,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0
4,27996267,0.0,0.0,0.0,12.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535084,20364112,0.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
535085,29974575,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
535086,23831430,0.0,0.0,0.0,1.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
535087,28258130,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
535088,28258130,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [29]:
chart_pharmacy_label_test = pd.DataFrame()
# Merge data_test with df_pharmacy 

chart_pharmacy_label_test = pd.DataFrame(chart_data_test['hadm_id']).merge(df_pharmacy, on='hadm_id', how='left')

In [30]:
chart_pharmacy_label_test

,hadm_id,23.4% Sodium Chloride,ALPRAZolam,AcetaZOLamide,Acetaminophen,Acetaminophen (Liquid),Acetaminophen IV,Acetaminophen w/Codeine,Acetaminophen-Caff-Butalbital,Acetylcysteine (IV),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,29974575,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,24104168,0.0,0.0,0.0,2.0,0.0,1.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,27996267,0.0,0.0,0.0,12.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,28258130,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,24540843,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133768,29276678,0.0,0.0,0.0,7.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
133769,29974575,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
133770,21255400,0.0,0.0,0.0,4.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
133771,22987108,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
133772,21027282,0.0,0.0,0.0,2.0,1.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
chart_prescriptions_label_train = pd.DataFrame()
# Merge data_train with df_prescriptions

chart_prescriptions_label_train = pd.DataFrame(chart_data_train['hadm_id']).merge(df_prescriptions, on='hadm_id', how='left')

In [32]:
chart_prescriptions_label_train

,hadm_id,*NF* Ertapenem Sodium,0.45% Sodium Chloride,0.83% Sodium Chloride,0.9% NaCl (EXCEL/ViaFLO BAG),0.9% Sodium Chloride,0.9% Sodium Chloride (Mini Bag Plus),23.4% Sodium Chloride,5% Dextrose,5% Dextrose (EXCEL BAG),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,20626031,0.0,0.0,1.0,0.0,5.0,0.0,0.0,4.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,25926192,0.0,0.0,0.0,0.0,6.0,0.0,0.0,7.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,29295881,0.0,1.0,0.0,0.0,6.0,2.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,28662225,0.0,0.0,0.0,0.0,9.0,2.0,0.0,9.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0
4,27996267,0.0,0.0,0.0,0.0,7.0,2.0,0.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535084,20364112,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
535085,29974575,0.0,0.0,0.0,0.0,3.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
535086,23831430,0.0,3.0,0.0,0.0,20.0,9.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
535087,28258130,0.0,0.0,0.0,0.0,22.0,8.0,0.0,22.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
535088,28258130,0.0,0.0,0.0,0.0,22.0,8.0,0.0,22.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [33]:
chart_prescriptions_label_test = pd.DataFrame()
# Merge data_test with df_prescriptions

chart_prescriptions_label_test = pd.DataFrame(chart_data_test['hadm_id']).merge(df_prescriptions, on='hadm_id', how='left')

In [34]:
chart_prescriptions_label_test

,hadm_id,*NF* Ertapenem Sodium,0.45% Sodium Chloride,0.83% Sodium Chloride,0.9% NaCl (EXCEL/ViaFLO BAG),0.9% Sodium Chloride,0.9% Sodium Chloride (Mini Bag Plus),23.4% Sodium Chloride,5% Dextrose,5% Dextrose (EXCEL BAG),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,29974575,0.0,0.0,0.0,0.0,3.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,24104168,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,27996267,0.0,0.0,0.0,0.0,7.0,2.0,0.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,28258130,0.0,0.0,0.0,0.0,22.0,8.0,0.0,22.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,24540843,0.0,0.0,0.0,0.0,31.0,1.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133768,29276678,0.0,0.0,0.0,0.0,34.0,9.0,0.0,16.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
133769,29974575,0.0,0.0,0.0,0.0,3.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
133770,21255400,0.0,0.0,0.0,0.0,3.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
133771,22987108,0.0,0.0,0.0,0.0,18.0,17.0,0.0,10.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
133772,21027282,0.0,0.0,0.0,0.0,10.0,1.0,0.0,17.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [35]:
chart_pharmacy_label_train.to_csv('chart_pharmacy_label_train.csv', index=False)
chart_pharmacy_label_test.to_csv('chart_pharmacy_label_test.csv', index=False)
chart_prescriptions_label_train.to_csv('chart_prescriptions_label_train.csv', index=False)
chart_prescriptions_label_test.to_csv('chart_prescriptions_label_test.csv', index=False)

### icustays

Records which icu care unit a patient stayed in and for how long
Not relevant

### ingredientevents

Ingredients of the administered meds
Should not be used to predict the med

### inputevents

Info on continuous infusions or intermittent administrations

Not medication (see d_items for link on itemid) so can use

In [132]:
file = "icu/inputevents.csv"
full_path = path + file

df_input = pd.read_csv(full_path)

In [133]:
df_input.head()

,subject_id,hadm_id,stay_id,caregiver_id,starttime,endtime,storetime,itemid,amount,amountuom,...,ordercomponenttypedescription,ordercategorydescription,patientweight,totalamount,totalamountuom,isopenbag,continueinnextdept,statusdescription,originalamount,originalrate
0,10005817,20626031,32604416,4793,2132-12-16 19:50:00,2132-12-16 19:51:00,2132-12-16 19:50:00,225798,1.0,dose,...,Main order parameter,Drug Push,91.0,500.0,ml,0,0,FinishedRunning,1.0,1.000000
1,10005817,20626031,32604416,92805,2132-12-15 20:15:00,2132-12-15 20:16:00,2132-12-15 20:11:00,225798,1.0,dose,...,Main order parameter,Drug Push,91.0,500.0,ml,0,0,FinishedRunning,1.0,1.000000
2,10005817,20626031,32604416,20310,2132-12-17 09:15:00,2132-12-17 09:16:00,2132-12-17 09:28:00,225798,1.0,dose,...,Main order parameter,Drug Push,91.0,500.0,ml,0,0,FinishedRunning,1.0,1.000000
3,10005817,20626031,32604416,79166,2132-12-16 09:36:00,2132-12-16 09:37:00,2132-12-16 09:37:00,225798,1.0,dose,...,Main order parameter,Drug Push,91.0,500.0,ml,0,0,FinishedRunning,1.0,1.000000
4,10005817,20626031,32604416,92805,2132-12-15 20:10:00,2132-12-15 21:10:00,2132-12-15 20:10:00,221456,2.0,grams,...,Additives ...,Continuous IV,91.0,100.0,ml,0,0,FinishedRunning,2.0,0.033333

In [146]:
df_input['secondaryordercategoryname'].value_counts()

02-Fluids (Crystalloids)    11166
Additive (Crystalloid)       2538
Additives (EN)                397
Additives (PN)                 43
Name: secondaryordercategoryname, dtype: int64

Drop: subject_id, starttime, endtime, storetime, orderid, linkorderid, continueinnextdept, stay_id, caregiver_id,
totalamountuom, statusdescription
Encode: amountuom, ordercategoryname, ordercomponenttypedescription, ordercategorydescription, itemid
Impute with 0: rate, totalamount
Impute with N/A and encode: rateuom, secondaryordercategoryname

In [147]:
# Make a duration feature using endtime-starttime

# Convert to datetime
df_input['endtime'] = pd.to_datetime(df_input['endtime'], format='%Y-%m-%d %H:%M:%S')
df_input['starttime'] = pd.to_datetime(df_input['starttime'], format='%Y-%m-%d %H:%M:%S')


df_input['duration'] = df_input['endtime'] - df_input['starttime']

# Fill any non time values
df_input['duration'] = df_input['duration'].fillna(pd.Timedelta(0))

In [148]:
# Drop 
df_input = df_input.drop(columns=['subject_id','stay_id','starttime','endtime','storetime','orderid','linkorderid',
                                  'continueinnextdept','totalamountuom', 'stay_id','caregiver_id','statusdescription'])

In [149]:
# Impute with N/A and encode
df_input['rateuom'] = df_input['rateuom'].fillna('N/A')
df_input['secondaryordercategoryname'] = df_input['secondaryordercategoryname'].fillna('N/A')
df_input = pd.get_dummies(df_input, columns=['rateuom','secondaryordercategoryname','amountuom','ordercategoryname',
                                            'ordercomponenttypedescription','ordercategorydescription','itemid'])

In [150]:
# Impute with 0
df_input['rate'] = df_input['rate'].fillna(0)
df_input['totalamount'] = df_input['totalamount'].fillna(0)

In [151]:
df_input = df_input.dropna()

#### Split into train and test

In [152]:
data = df_input

# Split the dataset into training and testing sets
input_data_train, input_data_test = train_test_split(data, test_size=0.2, random_state=42)

# Print the shapes of the resulting training and testing sets
print("Training set shape:", input_data_train.shape)
print("Testing set shape:", input_data_test.shape)

Training set shape: (16323, 216)
Testing set shape: (4081, 216)

In [153]:
# # uncomment and run if changes are made

# input_data_train.to_csv('input_data_train.csv', index=False)
# input_data_test.to_csv('input_data_test.csv', index=False)

In [4]:
file = "input_data_train.csv"
full_path = path + file

input_data_train = pd.read_csv(full_path)

input_data_train

,hadm_id,amount,rate,patientweight,totalamount,isopenbag,originalamount,originalrate,duration,rateuom_N/A,...,itemid_229072,itemid_229233,itemid_229295,itemid_229296,itemid_229297,itemid_229420,itemid_229615,itemid_229616,itemid_229639,itemid_229654
0,24540843,1.168952,2.504898,76.0,100.0,0,87.337433,2.500000,0 days 00:28:00,0,...,0,0,0,0,0,0,0,0,0,0
1,20755971,13.312397,15.070639,67.0,250.0,0,189.638840,15.075360,0 days 00:53:00,0,...,0,0,0,0,0,0,0,0,0,0
2,28157142,2.000000,0.000000,57.8,50.0,0,2.000000,0.033333,0 days 01:00:00,1,...,0,0,0,0,0,0,0,0,0,0
3,22130791,39.699999,2.408493,59.5,100.0,0,39.699997,2.404872,0 days 16:29:00,0,...,0,0,0,0,0,0,0,0,0,0
4,27617929,1.000000,0.000000,88.4,50.0,0,1.000000,1.000000,0 days 00:01:00,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16318,28889419,1000.000000,0.000000,72.5,0.0,0,1000.000000,999.999939,0 days 00:01:00,1,...,0,0,0,0,0,0,0,0,0,0
16319,24982426,170.611855,13.965500,64.1,250.0,0,249.999985,14.000000,0 days 12:13:00,0,...,0,0,0,0,0,0,0,0,0,0
16320,22429197,759.000003,60.238093,120.0,100.0,0,758.999939,60.141621,0 days 01:45:00,0,...,0,0,0,0,0,0,0,0,0,0
16321,25926192,257.083327,25.000000,64.9,500.0,0,500.000031,25.000000,0 days 10:17:00,0,...,0,0,0,0,0,0,0,0,0,0
16322,28998349,99.999998,100.000000,143.0,100.0,0,100.000000,100.000000,0 days 01:00:00,0,...,0,0,0,0,0,0,0,0,0,0

#### Dimensionality reduction

In [ ]:
# Fine

#### Target table (train and test)

In [112]:
input_pharmacy_label_train = pd.DataFrame()
# Merge data_train with df_pharmacy 

input_pharmacy_label_train = pd.DataFrame(input_data_train['hadm_id']).merge(df_pharmacy, on='hadm_id', how='left')

In [113]:
input_pharmacy_label_train

,hadm_id,23.4% Sodium Chloride,ALPRAZolam,AcetaZOLamide,Acetaminophen,Acetaminophen (Liquid),Acetaminophen IV,Acetaminophen w/Codeine,Acetaminophen-Caff-Butalbital,Acetylcysteine (IV),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,24540843,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,20755971,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,28157142,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,22130791,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,27617929,0.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16318,28889419,0.0,0.0,0.0,4.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16319,24982426,0.0,0.0,0.0,2.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16320,22429197,0.0,0.0,0.0,0.0,2.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16321,25926192,0.0,0.0,0.0,4.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16322,28998349,0.0,0.0,4.0,1.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [114]:
file = "input_data_test.csv"
full_path = path + file

input_data_test = pd.read_csv(full_path)

input_pharmacy_label_test = pd.DataFrame()
# Merge data_test with df_pharmacy 

input_pharmacy_label_test = pd.DataFrame(input_data_test['hadm_id']).merge(df_pharmacy, on='hadm_id', how='left')

In [115]:
input_pharmacy_label_test

,hadm_id,23.4% Sodium Chloride,ALPRAZolam,AcetaZOLamide,Acetaminophen,Acetaminophen (Liquid),Acetaminophen IV,Acetaminophen w/Codeine,Acetaminophen-Caff-Butalbital,Acetylcysteine (IV),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,29281842,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20214994,0.0,0.0,0.0,2.0,4.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,26275841,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,22168393,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,22168393,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4076,27089790,0.0,0.0,0.0,5.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4077,20338077,0.0,0.0,0.0,2.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4078,24490144,0.0,0.0,0.0,5.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4079,28998349,0.0,0.0,4.0,1.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4080,20611640,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [116]:
input_prescriptions_label_train = pd.DataFrame()
# Merge data_train with df_prescriptions

input_prescriptions_label_train = pd.DataFrame(input_data_train['hadm_id']).merge(df_prescriptions, on='hadm_id', how='left')

In [117]:
input_prescriptions_label_train

,hadm_id,*NF* Ertapenem Sodium,0.45% Sodium Chloride,0.83% Sodium Chloride,0.9% NaCl (EXCEL/ViaFLO BAG),0.9% Sodium Chloride,0.9% Sodium Chloride (Mini Bag Plus),23.4% Sodium Chloride,5% Dextrose,5% Dextrose (EXCEL BAG),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,24540843,0.0,0.0,0.0,0.0,31.0,1.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,20755971,0.0,0.0,0.0,0.0,2.0,6.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,28157142,0.0,0.0,0.0,0.0,3.0,2.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,22130791,0.0,0.0,0.0,0.0,13.0,2.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,27617929,0.0,0.0,0.0,0.0,10.0,5.0,0.0,6.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16318,28889419,0.0,0.0,0.0,0.0,7.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16319,24982426,0.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16320,22429197,0.0,0.0,0.0,0.0,6.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16321,25926192,0.0,0.0,0.0,0.0,6.0,0.0,0.0,7.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16322,28998349,0.0,0.0,0.0,0.0,19.0,0.0,0.0,18.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [118]:
input_prescriptions_label_test = pd.DataFrame()
# Merge data_test with df_prescriptions

input_prescriptions_label_test = pd.DataFrame(input_data_test['hadm_id']).merge(df_prescriptions, on='hadm_id', how='left')

In [119]:
input_prescriptions_label_test

,hadm_id,*NF* Ertapenem Sodium,0.45% Sodium Chloride,0.83% Sodium Chloride,0.9% NaCl (EXCEL/ViaFLO BAG),0.9% Sodium Chloride,0.9% Sodium Chloride (Mini Bag Plus),23.4% Sodium Chloride,5% Dextrose,5% Dextrose (EXCEL BAG),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,29281842,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20214994,0.0,0.0,0.0,0.0,4.0,2.0,0.0,11.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,26275841,0.0,0.0,0.0,0.0,5.0,2.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,22168393,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,22168393,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4076,27089790,0.0,0.0,1.0,0.0,4.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4077,20338077,0.0,0.0,0.0,0.0,9.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4078,24490144,0.0,0.0,0.0,0.0,4.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4079,28998349,0.0,0.0,0.0,0.0,19.0,0.0,0.0,18.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4080,20611640,0.0,0.0,0.0,0.0,5.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [120]:
input_pharmacy_label_train.to_csv('input_pharmacy_label_train.csv', index=False)
input_pharmacy_label_test.to_csv('input_pharmacy_label_test.csv', index=False)
input_prescriptions_label_train.to_csv('input_prescriptions_label_train.csv', index=False)
input_prescriptions_label_test.to_csv('input_prescriptions_label_test.csv', index=False)

### outputevents

Note: Cross reference itemid with d_items to show what they actually mean because some of them seem to just describe body parts?

In [154]:
file = "icu/outputevents.csv"
full_path = path + file

df_output = pd.read_csv(full_path)

In [156]:
df_output['itemid'].value_counts()

226559    6685
226588     641
226560     496
227510     325
226606     223
226599     121
226582      92
226561      90
226576      66
226600      57
226575      55
226619      48
226627      42
226580      41
227511      36
226592      34
227488      32
227489      31
227701      23
226626      21
226571      20
226579      19
226633      18
226583      17
226590      15
226567      15
226589      15
226602      14
226601      13
226613      12
226607      12
226625       9
226573       9
226612       7
226631       3
226604       2
226570       1
226632       1
226628       1
Name: itemid, dtype: int64

Drop: subject_id, charttime, storetime, valueuom, stay_id, caregiver_id
Encode: itemid

In [55]:
# Make a days_since_admission feature using charttime-admittime 

# Convert to datetime
df_output['charttime'] = pd.to_datetime(df_output['charttime'], format='%Y-%m-%d %H:%M:%S')

# Add admittime column from other dataframe
df_output = df_output.merge(df_admittime, on='hadm_id', how='left')

df_output['days_since_admission'] = df_output['charttime'] - df_output['admittime']

# Fill any non time values
df_output['days_since_admission'] = df_output['days_since_admission'].fillna(pd.Timedelta(0))

# Drop the admission time column
df_output = df_output.drop(columns=['admittime'])

In [57]:
# Drop 
df_output = df_output.drop(columns=['subject_id','stay_id','charttime','storetime','storetime','valueuom','caregiver_id'])

In [58]:
#Encode
df_output = pd.get_dummies(df_output, columns=['itemid'])

#### Split into train and test

In [59]:
data = df_output

# Split the dataset into training and testing sets
output_data_train, output_data_test = train_test_split(data, test_size=0.2, random_state=42)

# Print the shapes of the resulting training and testing sets
print("Training set shape:", output_data_train.shape)
print("Testing set shape:", output_data_test.shape)

Training set shape: (7489, 43)
Testing set shape: (1873, 43)

In [60]:
# uncomment and run if changes are made

output_data_train.to_csv('output_data_train.csv', index=False)
output_data_test.to_csv('output_data_test.csv', index=False)

In [5]:
file = "output_data_train.csv"
full_path = path + file

output_data_train = pd.read_csv(full_path)

output_data_train

,hadm_id,value,days_since_admission,recording_delay,itemid_226559,itemid_226560,itemid_226561,itemid_226567,itemid_226570,itemid_226571,...,itemid_226627,itemid_226628,itemid_226631,itemid_226632,itemid_226633,itemid_227488,itemid_227489,itemid_227510,itemid_227511,itemid_227701
0,27617929,55,2 days 12:49:00,-1 days +23:51:00,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,21255400,25,5 days 05:05:00,0 days 01:44:00,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,25809882,150,1 days 06:51:00,0 days 00:00:00,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,28998349,110,4 days 10:37:00,0 days 00:08:00,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,25129047,50,4 days 13:51:00,0 days 00:48:00,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7484,24540843,0,1 days 16:26:00,0 days 00:07:00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7485,28166872,6,9 days 15:55:00,0 days 00:19:00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7486,22585261,200,0 days 15:35:00,0 days 02:31:00,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7487,21027282,125,6 days 04:02:00,0 days 00:00:00,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7488,20214994,30,3 days 14:00:00,-1 days +23:59:00,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

#### Dimensionality reduction

In [ ]:
# Fine

#### Target table (train and test)

In [121]:
output_pharmacy_label_train = pd.DataFrame()
# Merge data_train with df_pharmacy 

output_pharmacy_label_train = pd.DataFrame(output_data_train['hadm_id']).merge(df_pharmacy, on='hadm_id', how='left')

In [122]:
output_pharmacy_label_train

,hadm_id,23.4% Sodium Chloride,ALPRAZolam,AcetaZOLamide,Acetaminophen,Acetaminophen (Liquid),Acetaminophen IV,Acetaminophen w/Codeine,Acetaminophen-Caff-Butalbital,Acetylcysteine (IV),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,27617929,0.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,21255400,0.0,0.0,0.0,4.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,25809882,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,28998349,0.0,0.0,4.0,1.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,25129047,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7484,24540843,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7485,28166872,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7486,22585261,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7487,21027282,0.0,0.0,0.0,2.0,1.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7488,20214994,0.0,0.0,0.0,2.0,4.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [123]:
file = "output_data_test.csv"
full_path = path + file

output_data_test = pd.read_csv(full_path)

output_pharmacy_label_test = pd.DataFrame()
# Merge data_test with df_pharmacy 

output_pharmacy_label_test = pd.DataFrame(output_data_test['hadm_id']).merge(df_pharmacy, on='hadm_id', how='left')

In [124]:
output_pharmacy_label_test

,hadm_id,23.4% Sodium Chloride,ALPRAZolam,AcetaZOLamide,Acetaminophen,Acetaminophen (Liquid),Acetaminophen IV,Acetaminophen w/Codeine,Acetaminophen-Caff-Butalbital,Acetylcysteine (IV),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,23473524,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,29974575,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,28506150,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,28479513,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,25239799,0.0,0.0,0.0,6.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1868,20626031,0.0,0.0,0.0,4.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1869,28166872,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1870,20214994,0.0,0.0,0.0,2.0,4.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1871,28662225,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0
1872,21027282,0.0,0.0,0.0,2.0,1.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [125]:
output_prescriptions_label_train = pd.DataFrame()
# Merge data_train with df_prescriptions

output_prescriptions_label_train = pd.DataFrame(output_data_train['hadm_id']).merge(df_prescriptions, on='hadm_id', how='left')

In [126]:
output_prescriptions_label_train

,hadm_id,*NF* Ertapenem Sodium,0.45% Sodium Chloride,0.83% Sodium Chloride,0.9% NaCl (EXCEL/ViaFLO BAG),0.9% Sodium Chloride,0.9% Sodium Chloride (Mini Bag Plus),23.4% Sodium Chloride,5% Dextrose,5% Dextrose (EXCEL BAG),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,27617929,0.0,0.0,0.0,0.0,10.0,5.0,0.0,6.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,21255400,0.0,0.0,0.0,0.0,3.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,25809882,0.0,0.0,0.0,0.0,19.0,3.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,28998349,0.0,0.0,0.0,0.0,19.0,0.0,0.0,18.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,25129047,0.0,0.0,1.0,0.0,19.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7484,24540843,0.0,0.0,0.0,0.0,31.0,1.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7485,28166872,0.0,2.0,2.0,0.0,7.0,4.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7486,22585261,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7487,21027282,0.0,0.0,0.0,0.0,10.0,1.0,0.0,17.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7488,20214994,0.0,0.0,0.0,0.0,4.0,2.0,0.0,11.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [127]:
output_prescriptions_label_test = pd.DataFrame()
# Merge data_test with df_prescriptions

output_prescriptions_label_test = pd.DataFrame(output_data_test['hadm_id']).merge(df_prescriptions, on='hadm_id', how='left')

In [128]:
output_prescriptions_label_test

,hadm_id,*NF* Ertapenem Sodium,0.45% Sodium Chloride,0.83% Sodium Chloride,0.9% NaCl (EXCEL/ViaFLO BAG),0.9% Sodium Chloride,0.9% Sodium Chloride (Mini Bag Plus),23.4% Sodium Chloride,5% Dextrose,5% Dextrose (EXCEL BAG),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,23473524,0.0,0.0,0.0,0.0,4.0,6.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,29974575,0.0,0.0,0.0,0.0,3.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,28506150,0.0,0.0,0.0,0.0,4.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,28479513,0.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,25239799,0.0,0.0,0.0,0.0,2.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1868,20626031,0.0,0.0,1.0,0.0,5.0,0.0,0.0,4.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1869,28166872,0.0,2.0,2.0,0.0,7.0,4.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1870,20214994,0.0,0.0,0.0,0.0,4.0,2.0,0.0,11.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1871,28662225,0.0,0.0,0.0,0.0,9.0,2.0,0.0,9.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0
1872,21027282,0.0,0.0,0.0,0.0,10.0,1.0,0.0,17.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [129]:
output_pharmacy_label_train.to_csv('output_pharmacy_label_train.csv', index=False)
output_pharmacy_label_test.to_csv('output_pharmacy_label_test.csv', index=False)
output_prescriptions_label_train.to_csv('output_prescriptions_label_train.csv', index=False)
output_prescriptions_label_test.to_csv('output_prescriptions_label_test.csv', index=False)

### procedureevents

In [160]:
file = "icu/procedureevents.csv"
full_path = path + file

df_procedure_events = pd.read_csv(full_path)

In [161]:
df_procedure_events.head()

,subject_id,hadm_id,stay_id,caregiver_id,starttime,endtime,storetime,itemid,value,valueuom,...,orderid,linkorderid,ordercategoryname,ordercategorydescription,patientweight,isopenbag,continueinnextdept,statusdescription,ORIGINALAMOUNT,ORIGINALRATE
0,10027445,26275841,34499716,10712.0,2142-07-31 01:54:00,2142-08-02 10:44:00,2142-08-02 10:44:00,225792,3410.0,min,...,532221,532221,Ventilation,ContinuousProcess,103.0,1,0,FinishedRunning,3410.0,1
1,10027445,26275841,34499716,80518.0,2142-07-31 08:18:00,2142-08-03 15:10:00,2142-08-03 15:23:00,224263,4732.0,min,...,401769,401769,Invasive Lines,ContinuousProcess,103.0,1,0,FinishedRunning,4732.0,1
2,10027445,26275841,34499716,96407.0,2142-07-31 06:00:00,2142-08-03 06:03:00,2142-08-03 08:16:00,224275,4323.0,min,...,9714245,9714245,Peripheral Lines,ContinuousProcess,103.0,1,0,FinishedRunning,4323.0,1
3,10027445,26275841,34499716,96407.0,2142-07-31 02:00:00,2142-08-03 05:57:00,2142-08-03 08:15:00,224275,4557.0,min,...,2870557,2870557,Peripheral Lines,ContinuousProcess,103.0,1,0,FinishedRunning,4557.0,1
4,10027445,26275841,34499716,NaN,2142-08-03 08:00:00,2142-08-03 21:06:00,2142-08-03 21:06:00.090,224277,786.0,min,...,4920092,4920092,Peripheral Lines,ContinuousProcess,103.0,1,0,FinishedRunning,786.0,1

Drop: subject_id, starttime, endtime, storetime, orderid, linkorderid, continueinnextdept, stay_id, caregiver_id, statusdescription
Encode: valueuom, ordercategoryname, ordercategorydescription, itemid
Impute with N/A and encode: location, locationcategory

In [162]:
# Make a duration feature using endtime-starttime

# Convert to datetime
df_procedure_events['endtime'] = pd.to_datetime(df_procedure_events['endtime'], format='%Y-%m-%d %H:%M:%S')
df_procedure_events['starttime'] = pd.to_datetime(df_procedure_events['starttime'], format='%Y-%m-%d %H:%M:%S')


df_procedure_events['duration'] = df_procedure_events['endtime'] - df_procedure_events['starttime']

# Fill any non time values
df_procedure_events['duration'] = df_procedure_events['duration'].fillna(pd.Timedelta(0))

In [163]:
# Drop 
df_procedure_events = df_procedure_events.drop(columns=['subject_id','stay_id','starttime','endtime','storetime','orderid',
                                                        'linkorderid','continueinnextdept','caregiver_id',
                                                        'statusdescription'])

In [164]:
# Impute with N/A and encode
df_procedure_events['location'] = df_procedure_events['location'].fillna('N/A')
df_procedure_events['locationcategory'] = df_procedure_events['locationcategory'].fillna('N/A')
df_procedure_events = pd.get_dummies(df_procedure_events, columns=['location','locationcategory','valueuom',
                                                                   'ordercategoryname','ordercategorydescription',
                                                                   'itemid'])

#### Split into train and test

In [165]:
data = df_procedure_events

# Split the dataset into training and testing sets
procedure_events_data_train, procedure_events_data_test = train_test_split(data, test_size=0.2, random_state=42)

# Print the shapes of the resulting training and testing sets
print("Training set shape:", procedure_events_data_train.shape)
print("Testing set shape:", procedure_events_data_test.shape)

Training set shape: (1174, 159)
Testing set shape: (294, 159)

In [166]:
# # uncomment and run if changes are made

# procedure_events_data_train.to_csv('procedure_events_data_train.csv', index=False)
# procedure_events_data_test.to_csv('procedure_events_data_test.csv', index=False)

In [6]:
file = "procedure_events_data_train.csv"
full_path = path + file

procedure_events_data_train = pd.read_csv(full_path)

procedure_events_data_train

,hadm_id,value,patientweight,isopenbag,ORIGINALAMOUNT,ORIGINALRATE,duration,location_Left Accessory Basilic,location_Left Accessory Cephalic,location_Left Antecube,...,itemid_228130,itemid_228286,itemid_228715,itemid_229351,itemid_229380,itemid_229526,itemid_229532,itemid_229580,itemid_229581,itemid_229586
0,24181354,1.0,127.0,0,1.0,0,0 days 00:01:00,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,28166872,1.0,64.0,0,1.0,0,0 days 00:01:00,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,29974575,1.0,107.0,0,1.0,0,0 days 00:01:00,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,26048429,2479.0,80.0,1,2479.0,1,1 days 17:19:00,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,21027282,5061.0,91.0,1,5061.0,1,3 days 12:21:00,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1169,23403708,1.0,76.8,0,1.0,0,0 days 00:01:00,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1170,21027282,1.0,91.0,0,1.0,0,0 days 00:01:00,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1171,20297618,1687.0,97.0,1,1687.0,1,1 days 04:07:00,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1172,27487226,2481.0,127.7,1,2481.0,1,1 days 17:21:00,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1173,23403708,1.0,76.8,0,1.0,0,0 days 00:01:00,0,0,0,...,0,0,0,0,0,0,0,0,0,0

#### Dimensionality reduction

In [ ]:
# Fine

#### Target table (train and test)

In [130]:
procedure_events_pharmacy_label_train = pd.DataFrame()
# Merge data_train with df_pharmacy 

procedure_events_pharmacy_label_train = pd.DataFrame(procedure_events_data_train['hadm_id']).merge(df_pharmacy, on='hadm_id', how='left')

In [131]:
procedure_events_pharmacy_label_train

,hadm_id,23.4% Sodium Chloride,ALPRAZolam,AcetaZOLamide,Acetaminophen,Acetaminophen (Liquid),Acetaminophen IV,Acetaminophen w/Codeine,Acetaminophen-Caff-Butalbital,Acetylcysteine (IV),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,24181354,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,28166872,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,29974575,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,26048429,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,21027282,0.0,0.0,0.0,2.0,1.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1169,23403708,0.0,0.0,0.0,4.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1170,21027282,0.0,0.0,0.0,2.0,1.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1171,20297618,0.0,0.0,0.0,7.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1172,27487226,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1173,23403708,0.0,0.0,0.0,4.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [132]:
file = "procedure_events_data_test.csv"
full_path = path + file

procedure_events_data_test = pd.read_csv(full_path)

procedure_events_pharmacy_label_test = pd.DataFrame()
# Merge data_test with df_pharmacy 

procedure_events_pharmacy_label_test = pd.DataFrame(procedure_events_data_test['hadm_id']).merge(df_pharmacy, on='hadm_id', how='left')

In [133]:
procedure_events_pharmacy_label_test

,hadm_id,23.4% Sodium Chloride,ALPRAZolam,AcetaZOLamide,Acetaminophen,Acetaminophen (Liquid),Acetaminophen IV,Acetaminophen w/Codeine,Acetaminophen-Caff-Butalbital,Acetylcysteine (IV),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,28998349,0.0,0.0,4.0,1.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,20321825,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,28998349,0.0,0.0,4.0,1.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,23819016,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,29600294,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,22987108,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
290,29366372,0.0,0.0,0.0,4.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
291,20338077,0.0,0.0,0.0,2.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
292,22756440,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
293,24181354,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [134]:
procedure_events_prescriptions_label_train = pd.DataFrame()
# Merge data_train with df_prescriptions

procedure_events_prescriptions_label_train = pd.DataFrame(procedure_events_data_train['hadm_id']).merge(df_prescriptions, on='hadm_id', how='left')

In [135]:
procedure_events_prescriptions_label_train

,hadm_id,*NF* Ertapenem Sodium,0.45% Sodium Chloride,0.83% Sodium Chloride,0.9% NaCl (EXCEL/ViaFLO BAG),0.9% Sodium Chloride,0.9% Sodium Chloride (Mini Bag Plus),23.4% Sodium Chloride,5% Dextrose,5% Dextrose (EXCEL BAG),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,24181354,0.0,0.0,0.0,0.0,8.0,6.0,0.0,18.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,28166872,0.0,2.0,2.0,0.0,7.0,4.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,29974575,0.0,0.0,0.0,0.0,3.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,26048429,0.0,0.0,0.0,0.0,4.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,21027282,0.0,0.0,0.0,0.0,10.0,1.0,0.0,17.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1169,23403708,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1170,21027282,0.0,0.0,0.0,0.0,10.0,1.0,0.0,17.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1171,20297618,0.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1172,27487226,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1173,23403708,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [136]:
procedure_events_prescriptions_label_test = pd.DataFrame()
# Merge data_test with df_prescriptions

procedure_events_prescriptions_label_test = pd.DataFrame(procedure_events_data_test['hadm_id']).merge(df_prescriptions, on='hadm_id', how='left')

In [137]:
procedure_events_prescriptions_label_test

,hadm_id,*NF* Ertapenem Sodium,0.45% Sodium Chloride,0.83% Sodium Chloride,0.9% NaCl (EXCEL/ViaFLO BAG),0.9% Sodium Chloride,0.9% Sodium Chloride (Mini Bag Plus),23.4% Sodium Chloride,5% Dextrose,5% Dextrose (EXCEL BAG),...,moxifloxacin,nitroglycerin,quiniDINE Gluconate E.R.,rifAXIMin,riluzole,ruxolitinib,sevelamer CARBONATE,traZODONE,vancomycin,venetoclax
0,28998349,0.0,0.0,0.0,0.0,19.0,0.0,0.0,18.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,20321825,0.0,0.0,0.0,0.0,3.0,2.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,28998349,0.0,0.0,0.0,0.0,19.0,0.0,0.0,18.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,23819016,0.0,0.0,0.0,0.0,1.0,2.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,29600294,0.0,0.0,0.0,2.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,22987108,0.0,0.0,0.0,0.0,18.0,17.0,0.0,10.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
290,29366372,0.0,0.0,0.0,0.0,4.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
291,20338077,0.0,0.0,0.0,0.0,9.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
292,22756440,0.0,0.0,0.0,0.0,7.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
293,24181354,0.0,0.0,0.0,0.0,8.0,6.0,0.0,18.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [138]:
procedure_events_pharmacy_label_train.to_csv('procedure_events_pharmacy_label_train.csv', index=False)
procedure_events_pharmacy_label_test.to_csv('procedure_events_pharmacy_label_test.csv', index=False)
procedure_events_prescriptions_label_train.to_csv('procedure_events_prescriptions_label_train.csv', index=False)
procedure_events_prescriptions_label_test.to_csv('procedure_events_prescriptions_label_test.csv', index=False)